import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "es" | "zh" | "hi" | "ru" | "ar";

interface LanguageInfo {
  code: Language;
  name: string;
  flag: string;
}

export const languages: LanguageInfo[] = [
  { code: "en", name: "English", flag: "🇺🇸" },
  { code: "es", name: "Español", flag: "🇪🇸" },
  { code: "zh", name: "中文", flag: "🇨🇳" },
  { code: "hi", name: "हिन्दी", flag: "🇮🇳" },
  { code: "ru", name: "Русский", flag: "🇷🇺" },
  { code: "ar", name: "العربية", flag: "🇮🇷" },
];

const translations: Record<Language, Record<string, string>> = {
  en: {
    "app.title": "PokeBit",
    "app.subtitle": "A child's game.",
    "main.generate": "GENERATE NEW VAULT",
    "main.generate12": "GENERATE VAULT (12 WORDS)",
    "main.generate24": "GENERATE VAULT (24 WORDS)",
    "main.import": "IMPORT VAULT",
    "main.securityTitle": "Local Security",
    "main.securityText": "All keys are generated locally on your device. They are never sent to external servers.",
    "main.footer": "©2026 PokeBit  •  Designed by doctor.bitcoin  •  A child's game.",
    "main.privacyLink": "Privacy Policy",
    "main.downloadExtension": "Download Chrome Extension",
    "generate.title": "🔐 Vault Generated",
    "generate.subtitle": "Your seed phrase and derived keys",
    "generate.derivedAccounts": "🛡️ Derived Accounts",
    "generate.protectVault": "🔒 Protect Vault",
    "generate.howItWorks": "How does it work?",
    "generate.helpTitle": "Military Grade Encryption",
    "generate.helpText": "Using our military-grade encryption technology (AES-256), your wallet information will be protected by your password in an easily exportable file.\n\nWe recommend attaching the file to an email along with other files (mixing effect) and sending it to yourself or others. This way, you'll have your wallet information in the cloud, accessible simply by accessing your email or asking the person who sent you the email to resend it with the attachments.\n\nThis way, you'll never lose access to your wallets while ensuring a high level of security.",
    "generate.helpWarning": "Note: We are not responsible for lost passwords. Without the password, the encrypted wallet information cannot be accessed.",
    "generate.passwordPlaceholder": "Password (min. 8 characters)",
    "generate.repeatPassword": "Repeat password",
    "generate.exportVault": "Export Vault (.aes)",
    "generate.generateNew": "Generate New",
    "generate.words": "words",
    "generate.back": "Back to Home",
    "generate.loading": "Generating Vault",
    "generate.loadingMsg": "High Entropy Generation",
    "generate.success": "Vault generated successfully",
    "generate.exported": "Encrypted file exported successfully",
    "generate.errorPassword": "You must enter a password",
    "generate.errorPasswordLength": "Password must be at least 8 characters",
    "generate.errorConfirm": "You must confirm the password",
    "generate.errorMatch": "Passwords do not match",
    "import.title": "Import Vault",
    "import.subtitle": "Restore your wallet from an encrypted file",
    "import.fileLabel": "📁 Vault File",
    "import.dragHere": "Drag your file here",
    "import.clickSelect": "or click to select",
    "import.onlyAes": "Only .aes files",
    "import.passwordLabel": "🔒 Decryption Password",
    "import.passwordPlaceholder": "Enter the vault password...",
    "import.importButton": "IMPORT VAULT",
    "import.importing": "Decrypting...",
    "import.success": "Vault decrypted successfully",
    "import.successMsg": "Your wallet has been restored",
    "import.back": "Back to Popup",
    "import.errorFile": "You must select a vault file",
    "import.errorPassword": "You must enter the password",
    "import.errorPasswordLength": "Password must be at least 8 characters",
    "import.errorFormat": "File must have .aes extension",
    "import.errorInvalid": "Invalid file or incorrect password",
    "import.reset": "Reset",
    "import.resetTitle": "Confirm Reset",
    "import.resetFinalTitle": "Final Confirmation",
    "import.resetWarning1": "Are you sure you want to reset? This will clear the current wallet from this view.",
    "import.resetWarning2": "This is your LAST WARNING. The wallet information will be cleared from this session. Make sure you have exported the vault if needed.",
    "import.resetSuccess": "Wallet reset successfully",
    "import.cancel": "Cancel",
    "import.continue": "Continue",
    "import.confirmReset": "Yes, Reset",
    "import.backMenu": "Back to Menu",
    "import.exportNewPassword": "Export with New Password",
    "import.newPassword": "New password",
    "import.repeatNewPassword": "Repeat new password",
    "import.exportButton": "Export Vault",
    "password.weak": "Weak password",
    "password.medium": "Medium password",
    "password.strong": "Strong password",
    "seedPhrase.title": "🌱 Recovery Phrase",
    "seedPhrase.warning": "Never share this phrase. Anyone with access can steal your funds.",
    "seedPhrase.copied": "Seed phrase copied!",
    "crypto.privateKey": "Private Key",
    "crypto.publicAddress": "Public Address",
    "crypto.copied": "Copied!",
    "bip39.question": "What is BIP-39?",
    "bip39.title": "BIP-39 Standard",
    "bip39.paragraph1": "The BIP-39 dictionary consists of 2048 English words, carefully chosen to respect the rule that the first 4 characters uniquely identify each word (no two words share the same first 4 letters) and to avoid using words that sound the same phonetically even if spelled differently. Additionally, the minimum word length is 3 letters. Each word in the dictionary is encoded with 11 bits.",
    "bip39.paragraph2": "Our phrase generation system offers a unique high-entropy system in which the probability of each word occupying a position within the phrase is uniform and equal to 1/2048.",
    "bip39.note": "Remember always the motto: Your keys, Your Cryptos.",
    "derivation.question": "What is this?",
    "derivation.title": "Key Derivation Process",
    "derivation.paragraph1": "Hierarchical Deterministic (HD) derivation allows generating multiple key pairs from a single seed phrase. Using the BIP-32/BIP-44/BIP-84 standards, a master key is derived from the mnemonic using PBKDF2 with 2048 iterations.",
    "derivation.paragraph2": "From the master key, child keys are derived following specific paths. For Ethereum we use m/44'/60'/0'/0/0 and for Bitcoin m/84'/0'/0'/0/0 (native SegWit). The private key is a 256-bit random number that serves as the 'secret' to sign transactions.",
    "derivation.paragraph3": "The public address is derived from the private key using elliptic curve cryptography (secp256k1). For Ethereum, a Keccak-256 hash is applied to the public key. For Bitcoin, SHA-256 and RIPEMD-160 hashes are applied, followed by Bech32 encoding to obtain the bc1q... address.",
    "derivation.note": "This one-way process ensures that it's impossible to obtain the private key from the public address.",
    "importInfo.question": "How does it work?",
    "importInfo.title": "Import/Export System",
    "importInfo.paragraph1": "Our system fulfills a triple function of wallet generation, export, and import with a very special format designed in our laboratories.",
    "importInfo.paragraph2": "The requirements to carry out a correct wallet import are two: remember the encryption password and have performed the encryption (export) from our application.",
    "importInfo.note": "The file will have the .aes extension and the file name is irrelevant to the decryption process, so you can customize the file name to your liking.",
    "demo.badge": "Chrome Extension Mockup",
    "demo.title": "PokeBit Extension",
    "demo.subtitle": "Flow preview: Initial Popup → Generation View (popup) → Import View (new tab)",
    "demo.popupSize": "Popup View: 420px",
    "demo.viewTab": "View Full Tab View",
    "demo.architecture": "📐 MVC Architecture",
    "demo.model": "Model:",
    "demo.modelDesc": "src/lib/model.ts - Generation and derivation logic",
    "demo.views": "Views:",
    "demo.viewsDesc": "src/views/ - PopupMainView, PopupGenerateView, TabImportView",
    "demo.controller": "Controller:",
    "demo.controllerDesc": "React components handle events",
    "privacy.back": "Back",
    "privacy.title": "Privacy Policy",
    "privacy.subtitle": "PokeBit - High Entropy Wallet Generator. A child's game.",
    "privacy.lastUpdated": "Last updated:",
    "privacy.section1.title": "1. Introduction",
    "privacy.section1.text": "PokeBit is a browser extension designed to generate and manage cryptocurrency wallets securely. This privacy policy explains how we handle (or rather, how we DON'T handle) your personal data.",
    "privacy.section2.title": "2. Data We DO NOT Collect",
    "privacy.section2.text": "PokeBit is designed with a total privacy approach. We do not collect, store, or transmit any personal data. Specifically:",
    "privacy.section2.items": "We don't collect seed phrases|We don't collect private keys|We don't collect wallet addresses|We don't collect encryption passwords|We don't collect usage information or analytics|We don't collect IP addresses|We don't collect device information|We don't use tracking cookies",
    "privacy.section3.title": "3. 100% Local Processing",
    "privacy.section3.text": "All PokeBit functionality runs exclusively on your local device:",
    "privacy.section3.items": "Wallet generation: Seed phrases are generated using local cryptographic entropy|Key derivation: Private and public keys are derived locally using BIP-32/BIP-44/BIP-84 standards|Encryption: .aes files are encrypted locally with AES-256|Storage: Data is only saved if you choose to export a file to your device",
    "privacy.section4.title": "4. No External Connections",
    "privacy.section4.text": "PokeBit does not make any connections to external servers. The extension works completely offline once installed. There are no:",
    "privacy.section4.items": "Backend servers|Third-party APIs|Analytics services|Advertising services|Cloud synchronization",
    "privacy.section5.title": "5. Extension Permissions",
    "privacy.section5.text": "PokeBit requires NO special browser permissions. The extension operates entirely within its own context:",
    "privacy.section5.items": "No access to your browsing history|No access to your tabs or windows|No access to your personal data|Language and theme preferences are stored locally using standard browser storage (localStorage)",
    "privacy.section6.title": "6. Security",
    "privacy.section6.text": "The security of your crypto assets depends exclusively on you:",
    "privacy.section6.items": "Keep your seed phrase in a secure offline place|Use strong passwords to encrypt your .aes files|Never share your seed phrase or private keys|Always verify you're using the official extension",
    "privacy.section7.title": "7. Open Source",
    "privacy.section7.text": "PokeBit source code is available for public audit. You can personally verify that there is no data transmission by reviewing the code.",
    "privacy.section8.title": "8. Changes to This Policy",
    "privacy.section8.text": "If we make changes to this privacy policy, we will update the 'last updated' date at the top of this page.",
    "privacy.section9.title": "9. Contact",
    "privacy.section9.text": "If you have questions about this privacy policy, you can contact us at:",
    "privacy.summary": "Summary: PokeBit does not collect, store, or transmit any data. All processing occurs locally on your device. Your keys, your cryptos.",
    "privacy.footer": "PokeBit | doctor.bitcoin | Cryptovault 2026",
  },
  es: {
    "app.title": "PokeBit",
    "app.subtitle": "A child's game.",
    "main.generate": "GENERAR NUEVA BÓVEDA",
    "main.generate12": "GENERAR BÓVEDA (12 PALABRAS)",
    "main.generate24": "GENERAR BÓVEDA (24 PALABRAS)",
    "main.import": "IMPORTAR BÓVEDA",
    "main.securityTitle": "Seguridad Local",
    "main.securityText": "Todas las claves se generan localmente en tu dispositivo. Nunca se envían a servidores externos.",
    "main.footer": "©2026 PokeBit  •  Designed by doctor.bitcoin  •  A child's game.",
    "main.privacyLink": "Política de Privacidad",
    "main.downloadExtension": "Descargar Extensión Chrome",
    "generate.title": "🔐 Bóveda Generada",
    "generate.subtitle": "Tu frase semilla y claves derivadas",
    "generate.derivedAccounts": "🛡️ Cuentas Derivadas",
    "generate.protectVault": "🔒 Proteger Bóveda",
    "generate.howItWorks": "¿Cómo funciona?",
    "generate.helpTitle": "Encriptación de Grado Militar",
    "generate.helpText": "Utilizando nuestra tecnología de encriptación de grado militar (AES-256) la información de sus billeteras estará protegida por su contraseña en un fichero fácilmente exportable.\n\nLe recomendamos que utilice el fichero para adjuntarlo en algún email junto a otros ficheros (efecto mezcla) y enviárselo a usted mismo u otras personas. De esta forma tendrá la información de sus billeteras en la nube disponible con tan solo acceder a su email o pedir a la persona que le envió el email que se lo reenvíe junto a los ficheros adjuntos.\n\nDe esta forma nunca perderá el acceso a sus billeteras asegurando al mismo tiempo un alto nivel de seguridad.",
    "generate.helpWarning": "Nota: No nos hacemos responsables de la pérdida de la contraseña. Sin la contraseña no se podrá acceder a la información de la billetera encriptada.",
    "generate.passwordPlaceholder": "Contraseña (mín. 8 caracteres)",
    "generate.repeatPassword": "Repetir contraseña",
    "generate.exportVault": "Exportar Bóveda (.aes)",
    "generate.generateNew": "Generar Nueva",
    "generate.words": "palabras",
    "generate.back": "Volver al Inicio",
    "generate.loading": "Generando Bóveda",
    "generate.loadingMsg": "Generación de Alta Entropía",
    "generate.success": "Bóveda generada exitosamente",
    "generate.exported": "Archivo encriptado exportado correctamente",
    "generate.errorPassword": "Debes introducir una contraseña",
    "generate.errorPasswordLength": "La contraseña debe tener al menos 8 caracteres",
    "generate.errorConfirm": "Debes confirmar la contraseña",
    "generate.errorMatch": "Las contraseñas no coinciden",
    "import.title": "Importar Bóveda",
    "import.subtitle": "Restaura tu wallet desde un archivo encriptado",
    "import.fileLabel": "📁 Archivo de Bóveda",
    "import.dragHere": "Arrastra tu archivo aquí",
    "import.clickSelect": "o haz clic para seleccionar",
    "import.onlyAes": "Solo archivos .aes",
    "import.passwordLabel": "🔒 Contraseña de Descifrado",
    "import.passwordPlaceholder": "Introduce la contraseña de la bóveda...",
    "import.importButton": "IMPORTAR BÓVEDA",
    "import.importing": "Descifrando...",
    "import.success": "Bóveda descifrada correctamente",
    "import.successMsg": "Tu wallet ha sido restaurada",
    "import.back": "Volver al Popup",
    "import.errorFile": "Debes seleccionar un archivo de bóveda",
    "import.errorPassword": "Debes introducir la contraseña",
    "import.errorPasswordLength": "La contraseña debe tener al menos 8 caracteres",
    "import.errorFormat": "El archivo debe tener extensión .aes",
    "import.errorInvalid": "Archivo inválido o contraseña incorrecta",
    "import.reset": "Reiniciar",
    "import.resetTitle": "Confirmar Reinicio",
    "import.resetFinalTitle": "Confirmación Final",
    "import.resetWarning1": "¿Estás seguro de que quieres reiniciar? Esto borrará la wallet actual de esta vista.",
    "import.resetWarning2": "Esta es tu ÚLTIMA ADVERTENCIA. La información de la wallet será borrada de esta sesión. Asegúrate de haber exportado la bóveda si es necesario.",
    "import.resetSuccess": "Wallet reiniciada correctamente",
    "import.cancel": "Cancelar",
    "import.continue": "Continuar",
    "import.confirmReset": "Sí, Reiniciar",
    "import.backMenu": "Volver al Menú",
    "import.exportNewPassword": "Exportar con Nueva Contraseña",
    "import.newPassword": "Nueva contraseña",
    "import.repeatNewPassword": "Repetir nueva contraseña",
    "import.exportButton": "Exportar Bóveda",
    "password.weak": "Contraseña débil",
    "password.medium": "Contraseña media",
    "password.strong": "Contraseña fuerte",
    "seedPhrase.title": "🌱 Frase de Recuperación",
    "seedPhrase.warning": "Nunca compartas esta frase. Cualquiera con acceso puede robar tus fondos.",
    "seedPhrase.copied": "¡Frase semilla copiada!",
    "crypto.privateKey": "Clave Privada",
    "crypto.publicAddress": "Dirección Pública",
    "crypto.copied": "¡Copiado!",
    "bip39.question": "¿Qué es BIP-39?",
    "bip39.title": "Estándar BIP-39",
    "bip39.paragraph1": "El diccionario BIP-39 consta de 2048 palabras en inglés, cuidadosamente elegidas para que respeten la norma de los 4 primeros caracteres identifican de forma única a cada palabra (no hay dos palabras con las primeras 4 letras iguales) y se evitan utilizar palabras que fonéticamente suenen igual aunque se escriban de forma distinta. Además la longitud mínima de palabra será de 3 letras. Cada palabra del diccionario es codificada con 11 bits.",
    "bip39.paragraph2": "Nuestro sistema de generación de frases ofrece un sistema único de alta entropía en el cual la probabilidad de que cada palabra ocupe una posición dentro de la frase es uniforme e igual a 1/2048.",
    "bip39.note": "Recuerde siempre el lema: Tus claves, Tus Cryptos.",
    "derivation.question": "¿Qué es esto?",
    "derivation.title": "Proceso de Derivación de Claves",
    "derivation.paragraph1": "La derivación Determinista Jerárquica (HD) permite generar múltiples pares de claves a partir de una única frase semilla. Usando los estándares BIP-32/BIP-44/BIP-84, se deriva una clave maestra del mnemónico utilizando PBKDF2 con 2048 iteraciones.",
    "derivation.paragraph2": "Desde la clave maestra, se derivan claves hijas siguiendo rutas específicas. Para Ethereum usamos m/44'/60'/0'/0/0 y para Bitcoin m/84'/0'/0'/0/0 (SegWit nativo). La clave privada es un número aleatorio de 256 bits que sirve como el 'secreto' para firmar transacciones.",
    "derivation.paragraph3": "La dirección pública se deriva de la clave privada usando criptografía de curva elíptica (secp256k1). Para Ethereum, se aplica un hash Keccak-256 a la clave pública. Para Bitcoin, se aplican hashes SHA-256 y RIPEMD-160, seguidos de codificación Bech32 para obtener la dirección bc1q...",
    "derivation.note": "Este proceso unidireccional asegura que es imposible obtener la clave privada desde la dirección pública.",
    "importInfo.question": "¿Cómo funciona?",
    "importInfo.title": "Sistema de Importación/Exportación",
    "importInfo.paragraph1": "Nuestro sistema cumple una triple función de generación, exportación e importación de wallets con un formato muy especial diseñado en nuestros laboratorios.",
    "importInfo.paragraph2": "Los requisitos para llevar a cabo una correcta importación de la wallet son dos: recordar la contraseña de encriptación y haber realizado el encriptado (exportación) desde nuestra aplicación.",
    "importInfo.note": "El fichero tendrá la extensión .aes y el nombre del fichero es indiferente para el proceso de desencriptación por lo que puede personalizar el nombre del fichero a su gusto.",
    "demo.badge": "Mockup de Extensión Chrome",
    "demo.title": "PokeBit Extension",
    "demo.subtitle": "Previsualización del flujo: Popup inicial → Vista generación (popup) → Vista importación (pestaña nueva)",
    "demo.popupSize": "Vista Popup: 420px",
    "demo.viewTab": "Ver Vista Tab Completa",
    "demo.architecture": "📐 Arquitectura MVC",
    "demo.model": "Model:",
    "demo.modelDesc": "src/lib/model.ts - Lógica de generación y derivación",
    "demo.views": "Views:",
    "demo.viewsDesc": "src/views/ - PopupMainView, PopupGenerateView, TabImportView",
    "demo.controller": "Controller:",
    "demo.controllerDesc": "Los componentes React manejan los eventos",
    "privacy.back": "Volver",
    "privacy.title": "Política de Privacidad",
    "privacy.subtitle": "PokeBit - Generador de Wallets de Alta Entropía. A child's game.",
    "privacy.lastUpdated": "Última actualización:",
    "privacy.section1.title": "1. Introducción",
    "privacy.section1.text": "PokeBit es una extensión de navegador diseñada para generar y gestionar wallets de criptomonedas de forma segura. Esta política de privacidad explica cómo manejamos (o más bien, cómo NO manejamos) sus datos personales.",
    "privacy.section2.title": "2. Datos que NO recopilamos",
    "privacy.section2.text": "PokeBit está diseñado con un enfoque de privacidad total. No recopilamos, almacenamos, ni transmitimos ningún dato personal. Específicamente:",
    "privacy.section2.items": "No recopilamos frases semilla (seed phrases)|No recopilamos claves privadas|No recopilamos direcciones de wallet|No recopilamos contraseñas de encriptación|No recopilamos información de uso o analíticas|No recopilamos direcciones IP|No recopilamos información del dispositivo|No utilizamos cookies de seguimiento",
    "privacy.section3.title": "3. Procesamiento 100% Local",
    "privacy.section3.text": "Toda la funcionalidad de PokeBit se ejecuta exclusivamente en su dispositivo local:",
    "privacy.section3.items": "Generación de wallets: Las frases semilla se generan usando entropía criptográfica local|Derivación de claves: Las claves privadas y públicas se derivan localmente usando estándares BIP-32/BIP-44/BIP-84|Encriptación: Los archivos .aes se encriptan localmente con AES-256|Almacenamiento: Los datos solo se guardan si usted decide exportar un archivo a su dispositivo",
    "privacy.section4.title": "4. Sin conexiones externas",
    "privacy.section4.text": "PokeBit no realiza ninguna conexión a servidores externos. La extensión funciona completamente offline una vez instalada. No hay:",
    "privacy.section4.items": "Servidores backend|APIs de terceros|Servicios de analítica|Servicios de publicidad|Sincronización en la nube",
    "privacy.section5.title": "5. Permisos de la extensión",
    "privacy.section5.text": "PokeBit NO requiere permisos especiales del navegador. La extensión opera completamente dentro de su propio contexto:",
    "privacy.section5.items": "Sin acceso a tu historial de navegación|Sin acceso a tus pestañas o ventanas|Sin acceso a tus datos personales|Las preferencias de idioma y tema se almacenan localmente usando el almacenamiento estándar del navegador (localStorage)",
    "privacy.section6.title": "6. Seguridad",
    "privacy.section6.text": "La seguridad de sus activos criptográficos depende exclusivamente de usted:",
    "privacy.section6.items": "Guarde su frase semilla en un lugar seguro offline|Use contraseñas fuertes para encriptar sus archivos .aes|Nunca comparta su frase semilla o claves privadas|Verifique siempre que está usando la extensión oficial",
    "privacy.section7.title": "7. Código abierto",
    "privacy.section7.text": "El código fuente de PokeBit está disponible para auditoría pública. Puede verificar personalmente que no existe ninguna transmisión de datos revisando el código.",
    "privacy.section8.title": "8. Cambios en esta política",
    "privacy.section8.text": "Si realizamos cambios en esta política de privacidad, actualizaremos la fecha de 'última actualización' en la parte superior de esta página.",
    "privacy.section9.title": "9. Contacto",
    "privacy.section9.text": "Si tiene preguntas sobre esta política de privacidad, puede contactarnos en:",
    "privacy.summary": "Resumen: PokeBit no recopila, almacena ni transmite ningún dato. Todo el procesamiento ocurre localmente en su dispositivo. Sus claves, sus cryptos.",
    "privacy.footer": "PokeBit | doctor.bitcoin | Cryptovault 2026",
  },
  zh: {
    "app.title": "PokeBit",
    "app.subtitle": "A child's game.",
    "main.generate": "生成新保险库",
    "main.generate12": "生成保险库（12个词）",
    "main.generate24": "生成保险库（24个词）",
    "main.import": "导入保险库",
    "main.securityTitle": "本地安全",
    "main.securityText": "所有密钥都在您的设备上本地生成。它们永远不会发送到外部服务器。",
    "main.footer": "©2026 PokeBit  •  Designed by doctor.bitcoin  •  A child's game.",
    "main.privacyLink": "隐私政策",
    "main.downloadExtension": "下载Chrome扩展",
    "generate.title": "🔐 保险库已生成",
    "generate.subtitle": "您的助记词和派生密钥",
    "generate.derivedAccounts": "🛡️ 派生账户",
    "generate.protectVault": "🔒 保护保险库",
    "generate.howItWorks": "它是如何工作的？",
    "generate.helpTitle": "军事级加密",
    "generate.helpText": "使用我们的军事级加密技术（AES-256），您的钱包信息将受到密码保护，存储在易于导出的文件中。\n\n我们建议将文件附加到电子邮件中，与其他文件一起（混合效果），发送给自己或他人。这样，您只需访问电子邮件或请求发送电子邮件的人重新发送附件，即可在云中获取您的钱包信息。\n\n这样，您将永远不会失去对钱包的访问权限，同时确保高水平的安全性。",
    "generate.helpWarning": "注意：我们不对丢失的密码负责。没有密码，将无法访问加密的钱包信息。",
    "generate.passwordPlaceholder": "密码（至少8个字符）",
    "generate.repeatPassword": "重复密码",
    "generate.exportVault": "导出保险库 (.aes)",
    "generate.generateNew": "生成新的",
    "generate.words": "个词",
    "generate.back": "返回主页",
    "generate.loading": "正在生成保险库",
    "generate.loadingMsg": "高熵生成",
    "generate.success": "保险库生成成功",
    "generate.exported": "加密文件导出成功",
    "generate.errorPassword": "您必须输入密码",
    "generate.errorPasswordLength": "密码必须至少8个字符",
    "generate.errorConfirm": "您必须确认密码",
    "generate.errorMatch": "密码不匹配",
    "import.title": "导入保险库",
    "import.subtitle": "从加密文件恢复您的钱包",
    "import.fileLabel": "📁 保险库文件",
    "import.dragHere": "将文件拖到这里",
    "import.clickSelect": "或点击选择",
    "import.onlyAes": "仅限 .aes 文件",
    "import.passwordLabel": "🔒 解密密码",
    "import.passwordPlaceholder": "输入保险库密码...",
    "import.importButton": "导入保险库",
    "import.importing": "正在解密...",
    "import.success": "保险库解密成功",
    "import.successMsg": "您的钱包已恢复",
    "import.back": "返回弹出窗口",
    "import.errorFile": "您必须选择保险库文件",
    "import.errorPassword": "您必须输入密码",
    "import.errorPasswordLength": "密码必须至少8个字符",
    "import.errorFormat": "文件必须是 .aes 格式",
    "import.errorInvalid": "文件无效或密码错误",
    "import.reset": "重置",
    "import.resetTitle": "确认重置",
    "import.resetFinalTitle": "最终确认",
    "import.resetWarning1": "您确定要重置吗？这将清除当前视图中的钱包。",
    "import.resetWarning2": "这是您的最后警告。钱包信息将从此会话中清除。如果需要，请确保已导出保险库。",
    "import.resetSuccess": "钱包重置成功",
    "import.cancel": "取消",
    "import.continue": "继续",
    "import.confirmReset": "是的，重置",
    "import.backMenu": "返回菜单",
    "import.exportNewPassword": "使用新密码导出",
    "import.newPassword": "新密码",
    "import.repeatNewPassword": "重复新密码",
    "import.exportButton": "导出保险库",
    "password.weak": "弱密码",
    "password.medium": "中等密码",
    "password.strong": "强密码",
    "seedPhrase.title": "🌱 恢复短语",
    "seedPhrase.warning": "永远不要分享这个短语。任何有访问权限的人都可以窃取您的资金。",
    "seedPhrase.copied": "助记词已复制！",
    "crypto.privateKey": "私钥",
    "crypto.publicAddress": "公共地址",
    "crypto.copied": "已复制！",
    "bip39.question": "什么是BIP-39？",
    "bip39.title": "BIP-39标准",
    "bip39.paragraph1": "BIP-39字典由2048个英语单词组成，经过精心挑选，以确保前4个字符唯一标识每个单词（没有两个单词共享相同的前4个字母），并避免使用发音相同但拼写不同的单词。此外，最小单词长度为3个字母。字典中的每个单词用11位编码。",
    "bip39.paragraph2": "我们的短语生成系统提供独特的高熵系统，其中每个单词在短语中占据某个位置的概率是均匀的，等于1/2048。",
    "bip39.note": "请记住座右铭：你的密钥，你的加密货币。",
    "derivation.question": "这是什么？",
    "derivation.title": "密钥派生过程",
    "derivation.paragraph1": "分层确定性（HD）派生允许从单个种子短语生成多个密钥对。使用BIP-32/BIP-44/BIP-84标准，通过PBKDF2进行2048次迭代从助记词派生主密钥。",
    "derivation.paragraph2": "从主密钥开始，按照特定路径派生子密钥。以太坊使用m/44'/60'/0'/0/0，比特币使用m/84'/0'/0'/0/0（原生SegWit）。私钥是一个256位随机数，用作签署交易的'秘密'。",
    "derivation.paragraph3": "公共地址通过椭圆曲线密码学（secp256k1）从私钥派生。对于以太坊，对公钥应用Keccak-256哈希。对于比特币，应用SHA-256和RIPEMD-160哈希，然后进行Bech32编码以获得bc1q...地址。",
    "derivation.note": "这个单向过程确保从公共地址无法获取私钥。",
    "importInfo.question": "这是如何工作的？",
    "importInfo.title": "导入/导出系统",
    "importInfo.paragraph1": "我们的系统具有钱包生成、导出和导入的三重功能，采用我们实验室设计的特殊格式。",
    "importInfo.paragraph2": "正确导入钱包的要求有两个：记住加密密码，并且已从我们的应用程序执行加密（导出）。",
    "importInfo.note": "文件将具有.aes扩展名，文件名对解密过程无关紧要，因此您可以根据喜好自定义文件名。",
    "demo.badge": "Chrome 扩展模型",
    "demo.title": "PokeBit 扩展",
    "demo.subtitle": "流程预览：初始弹出窗口 → 生成视图（弹出窗口）→ 导入视图（新标签页）",
    "demo.popupSize": "弹出视图：420px",
    "demo.viewTab": "查看完整标签视图",
    "demo.architecture": "📐 MVC 架构",
    "demo.model": "模型：",
    "demo.modelDesc": "src/lib/model.ts - 生成和派生逻辑",
    "demo.views": "视图：",
    "demo.viewsDesc": "src/views/ - PopupMainView, PopupGenerateView, TabImportView",
    "demo.controller": "控制器:",
    "demo.controllerDesc": "React 组件处理事件",
    "privacy.back": "返回",
    "privacy.title": "隐私政策",
    "privacy.subtitle": "PokeBit - 高熵钱包生成器. A child's game.",
    "privacy.lastUpdated": "最后更新：",
    "privacy.section1.title": "1. 介绍",
    "privacy.section1.text": "PokeBit是一个浏览器扩展，旨在安全地生成和管理加密货币钱包。本隐私政策解释了我们如何处理（或者更确切地说，如何不处理）您的个人数据。",
    "privacy.section2.title": "2. 我们不收集的数据",
    "privacy.section2.text": "PokeBit采用完全隐私方法设计。我们不收集、存储或传输任何个人数据。具体来说：",
    "privacy.section2.items": "我们不收集助记词|我们不收集私钥|我们不收集钱包地址|我们不收集加密密码|我们不收集使用信息或分析|我们不收集IP地址|我们不收集设备信息|我们不使用跟踪cookies",
    "privacy.section3.title": "3. 100%本地处理",
    "privacy.section3.text": "所有PokeBit功能都在您的本地设备上运行：",
    "privacy.section3.items": "钱包生成：使用本地加密熵生成助记词|密钥派生：使用BIP-32/BIP-44/BIP-84标准在本地派生私钥和公钥|加密：.aes文件使用AES-256在本地加密|存储：只有当您选择将文件导出到设备时才会保存数据",
    "privacy.section4.title": "4. 无外部连接",
    "privacy.section4.text": "PokeBit不会连接到任何外部服务器。扩展程序安装后完全离线工作。没有：",
    "privacy.section4.items": "后端服务器|第三方API|分析服务|广告服务|云同步",
    "privacy.section5.title": "5. 扩展权限",
    "privacy.section5.text": "PokeBit不需要任何特殊的浏览器权限。该扩展完全在其自己的上下文中运行：",
    "privacy.section5.items": "无法访问您的浏览历史|无法访问您的标签页或窗口|无法访问您的个人数据|语言和主题偏好使用标准浏览器存储（localStorage）本地保存",
    "privacy.section6.title": "6. 安全",
    "privacy.section6.text": "您的加密资产安全完全取决于您：",
    "privacy.section6.items": "将助记词保存在安全的离线位置|使用强密码加密您的.aes文件|永远不要分享您的助记词或私钥|始终验证您使用的是官方扩展程序",
    "privacy.section7.title": "7. 开源",
    "privacy.section7.text": "PokeBit源代码可供公众审计。您可以通过查看代码亲自验证不存在任何数据传输。",
    "privacy.section8.title": "8. 政策变更",
    "privacy.section8.text": "如果我们对本隐私政策进行更改，我们将更新本页面顶部的'最后更新'日期。",
    "privacy.section9.title": "9. 联系方式",
    "privacy.section9.text": "如果您对本隐私政策有疑问，可以通过以下方式联系我们：",
    "privacy.summary": "摘要：PokeBit不收集、存储或传输任何数据。所有处理都在您的设备上本地进行。您的密钥，您的加密货币。",
    "privacy.footer": "PokeBit | doctor.bitcoin | Cryptovault 2026",
  },
  hi: {
    "app.title": "PokeBit",
    "app.subtitle": "A child's game.",
    "main.generate": "नया वॉल्ट बनाएं",
    "main.generate12": "वॉल्ट बनाएं (12 शब्द)",
    "main.generate24": "वॉल्ट बनाएं (24 शब्द)",
    "main.import": "वॉल्ट आयात करें",
    "main.securityTitle": "स्थानीय सुरक्षा",
    "main.securityText": "सभी कुंजियां आपके डिवाइस पर स्थानीय रूप से उत्पन्न होती हैं। वे कभी बाहरी सर्वर पर नहीं भेजी जातीं।",
    "main.footer": "©2026 PokeBit  •  Designed by doctor.bitcoin  •  A child's game.",
    "main.privacyLink": "गोपनीयता नीति",
    "main.downloadExtension": "Chrome एक्सटेंशन डाउनलोड करें",
    "generate.title": "🔐 वॉल्ट बनाया गया",
    "generate.subtitle": "आपका सीड फ्रेज और व्युत्पन्न कुंजियां",
    "generate.derivedAccounts": "🛡️ व्युत्पन्न खाते",
    "generate.protectVault": "🔒 वॉल्ट सुरक्षित करें",
    "generate.howItWorks": "यह कैसे काम करता है?",
    "generate.helpTitle": "सैन्य ग्रेड एन्क्रिप्शन",
    "generate.helpText": "हमारी सैन्य-ग्रेड एन्क्रिप्शन तकनीक (AES-256) का उपयोग करके, आपकी वॉलेट जानकारी आपके पासवर्ड द्वारा आसानी से निर्यात योग्य फ़ाइल में सुरक्षित होगी।\n\nहम अनुशंसा करते हैं कि फ़ाइल को अन्य फ़ाइलों (मिश्रण प्रभाव) के साथ ईमेल में संलग्न करें और इसे स्वयं या दूसरों को भेजें। इस तरह, आपके पास क्लाउड में आपकी वॉलेट जानकारी होगी, बस अपने ईमेल तक पहुंचकर या उस व्यक्ति से संलग्नक के साथ पुनः भेजने के लिए कहकर।\n\nइस तरह, आप उच्च स्तर की सुरक्षा सुनिश्चित करते हुए अपने वॉलेट तक पहुंच कभी नहीं खोएंगे।",
    "generate.helpWarning": "नोट: हम खोए हुए पासवर्ड के लिए जिम्मेदार नहीं हैं। पासवर्ड के बिना, एन्क्रिप्टेड वॉलेट जानकारी तक पहुंच नहीं हो सकती।",
    "generate.passwordPlaceholder": "पासवर्ड (न्यूनतम 8 अक्षर)",
    "generate.repeatPassword": "पासवर्ड दोहराएं",
    "generate.exportVault": "वॉल्ट निर्यात करें (.aes)",
    "generate.generateNew": "नया बनाएं",
    "generate.words": "शब्द",
    "generate.back": "होम पर वापस जाएं",
    "generate.loading": "वॉल्ट बना रहे हैं",
    "generate.loadingMsg": "उच्च एन्ट्रॉपी जनरेशन",
    "generate.success": "वॉल्ट सफलतापूर्वक बनाया गया",
    "generate.exported": "एन्क्रिप्टेड फ़ाइल सफलतापूर्वक निर्यात की गई",
    "generate.errorPassword": "आपको पासवर्ड दर्ज करना होगा",
    "generate.errorPasswordLength": "पासवर्ड कम से कम 8 अक्षरों का होना चाहिए",
    "generate.errorConfirm": "आपको पासवर्ड की पुष्टि करनी होगी",
    "generate.errorMatch": "पासवर्ड मेल नहीं खाते",
    "import.title": "वॉल्ट आयात करें",
    "import.subtitle": "एन्क्रिप्टेड फ़ाइल से अपना वॉलेट पुनर्स्थापित करें",
    "import.fileLabel": "📁 वॉल्ट फ़ाइल",
    "import.dragHere": "अपनी फ़ाइल यहां खींचें",
    "import.clickSelect": "या चुनने के लिए क्लिक करें",
    "import.onlyAes": "केवल .aes फ़ाइलें",
    "import.passwordLabel": "🔒 डिक्रिप्शन पासवर्ड",
    "import.passwordPlaceholder": "वॉल्ट का पासवर्ड दर्ज करें...",
    "import.importButton": "वॉल्ट आयात करें",
    "import.importing": "डिक्रिप्ट हो रहा है...",
    "import.success": "वॉल्ट सफलतापूर्वक डिक्रिप्ट किया गया",
    "import.successMsg": "आपका वॉलेट पुनर्स्थापित हो गया है",
    "import.back": "पॉपअप पर वापस जाएं",
    "import.errorFile": "आपको वॉल्ट फ़ाइल चुननी होगी",
    "import.errorPassword": "आपको पासवर्ड दर्ज करना होगा",
    "import.errorPasswordLength": "पासवर्ड कम से कम 8 अक्षरों का होना चाहिए",
    "import.errorFormat": "फ़ाइल .aes प्रारूप में होनी चाहिए",
    "import.errorInvalid": "अमान्य फ़ाइल या गलत पासवर्ड",
    "import.reset": "रीसेट",
    "import.resetTitle": "रीसेट की पुष्टि करें",
    "import.resetFinalTitle": "अंतिम पुष्टि",
    "import.resetWarning1": "क्या आप वाकई रीसेट करना चाहते हैं? यह वर्तमान वॉलेट को इस व्यू से हटा देगा।",
    "import.resetWarning2": "यह आपकी अंतिम चेतावनी है। वॉलेट की जानकारी इस सत्र से हटा दी जाएगी। सुनिश्चित करें कि आपने जरूरत पड़ने पर वॉल्ट निर्यात कर लिया है।",
    "import.resetSuccess": "वॉलेट सफलतापूर्वक रीसेट किया गया",
    "import.cancel": "रद्द करें",
    "import.continue": "जारी रखें",
    "import.confirmReset": "हाँ, रीसेट करें",
    "import.backMenu": "मेनू पर वापस जाएं",
    "import.exportNewPassword": "नए पासवर्ड के साथ निर्यात करें",
    "import.newPassword": "नया पासवर्ड",
    "import.repeatNewPassword": "नया पासवर्ड दोहराएं",
    "import.exportButton": "वॉल्ट निर्यात करें",
    "password.weak": "कमजोर पासवर्ड",
    "password.medium": "मध्यम पासवर्ड",
    "password.strong": "मजबूत पासवर्ड",
    "seedPhrase.title": "🌱 रिकवरी फ्रेज",
    "seedPhrase.warning": "इस फ्रेज को कभी साझा न करें। इसका एक्सेस रखने वाला कोई भी आपके फंड चुरा सकता है।",
    "seedPhrase.copied": "सीड फ्रेज कॉपी किया गया!",
    "crypto.privateKey": "निजी कुंजी",
    "crypto.publicAddress": "सार्वजनिक पता",
    "crypto.copied": "कॉपी किया गया!",
    "bip39.question": "BIP-39 क्या है?",
    "bip39.title": "BIP-39 मानक",
    "bip39.paragraph1": "BIP-39 शब्दकोश में 2048 अंग्रेजी शब्द हैं, जिन्हें सावधानीपूर्वक चुना गया है ताकि पहले 4 अक्षर प्रत्येक शब्द को विशिष्ट रूप से पहचानें (कोई भी दो शब्द समान पहले 4 अक्षर साझा नहीं करते) और ध्वन्यात्मक रूप से समान लगने वाले शब्दों से बचा जाए भले ही वे अलग तरीके से लिखे गए हों। इसके अलावा, न्यूनतम शब्द लंबाई 3 अक्षर है। शब्दकोश में प्रत्येक शब्द 11 बिट्स के साथ एन्कोड किया गया है।",
    "bip39.paragraph2": "हमारी वाक्यांश पीढ़ी प्रणाली एक अद्वितीय उच्च-एन्ट्रॉपी प्रणाली प्रदान करती है जिसमें प्रत्येक शब्द के वाक्यांश में एक स्थान पर होने की संभावना समान और 1/2048 के बराबर है।",
    "bip39.note": "हमेशा याद रखें: आपकी चाबियाँ, आपकी क्रिप्टो।",
    "derivation.question": "यह क्या है?",
    "derivation.title": "कुंजी व्युत्पन्न प्रक्रिया",
    "derivation.paragraph1": "पदानुक्रमित निर्धारक (HD) व्युत्पन्न एकल बीज वाक्यांश से कई कुंजी जोड़े उत्पन्न करने की अनुमति देता है। BIP-32/BIP-44/BIP-84 मानकों का उपयोग करके, 2048 पुनरावृत्तियों के साथ PBKDF2 का उपयोग करके स्मृति सहायक से मास्टर कुंजी व्युत्पन्न की जाती है।",
    "derivation.paragraph2": "मास्टर कुंजी से, विशिष्ट पथों का अनुसरण करते हुए बाल कुंजियाँ व्युत्पन्न की जाती हैं। एथेरियम के लिए हम m/44'/60'/0'/0/0 और बिटकॉइन के लिए m/84'/0'/0'/0/0 (नेटिव SegWit) का उपयोग करते हैं। निजी कुंजी एक 256-बिट यादृच्छिक संख्या है जो लेनदेन पर हस्ताक्षर करने के लिए 'रहस्य' के रूप में कार्य करती है।",
    "derivation.paragraph3": "सार्वजनिक पता अण्डाकार वक्र क्रिप्टोग्राफी (secp256k1) का उपयोग करके निजी कुंजी से व्युत्पन्न होता है। एथेरियम के लिए, सार्वजनिक कुंजी पर Keccak-256 हैश लागू किया जाता है। बिटकॉइन के लिए, SHA-256 और RIPEMD-160 हैश लागू किए जाते हैं, उसके बाद bc1q... पता प्राप्त करने के लिए Bech32 एन्कोडिंग।",
    "derivation.note": "यह एकतरफा प्रक्रिया सुनिश्चित करती है कि सार्वजनिक पते से निजी कुंजी प्राप्त करना असंभव है।",
    "importInfo.question": "यह कैसे काम करता है?",
    "importInfo.title": "आयात/निर्यात प्रणाली",
    "importInfo.paragraph1": "हमारी प्रणाली हमारी प्रयोगशालाओं में डिज़ाइन किए गए एक बहुत विशेष प्रारूप के साथ वॉलेट पीढ़ी, निर्यात और आयात का तिहरा कार्य पूरा करती है।",
    "importInfo.paragraph2": "वॉलेट का सही आयात करने की आवश्यकताएं दो हैं: एन्क्रिप्शन पासवर्ड याद रखना और हमारे एप्लिकेशन से एन्क्रिप्शन (निर्यात) किया होना।",
    "importInfo.note": "फ़ाइल में .aes एक्सटेंशन होगा और फ़ाइल का नाम डिक्रिप्शन प्रक्रिया के लिए अप्रासंगिक है, इसलिए आप अपनी पसंद के अनुसार फ़ाइल का नाम अनुकूलित कर सकते हैं।",
    "demo.badge": "क्रोम एक्सटेंशन मॉकअप",
    "demo.title": "PokeBit एक्सटेंशन",
    "demo.subtitle": "फ्लो प्रीव्यू: प्रारंभिक पॉपअप → जनरेशन व्यू (पॉपअप) → आयात व्यू (नया टैब)",
    "demo.popupSize": "पॉपअप व्यू: 420px",
    "demo.viewTab": "पूर्ण टैब व्यू देखें",
    "demo.architecture": "📐 MVC आर्किटेक्चर",
    "demo.model": "मॉडल:",
    "demo.modelDesc": "src/lib/model.ts - जनरेशन और डेरिवेशन लॉजिक",
    "demo.views": "व्यूज:",
    "demo.viewsDesc": "src/views/ - PopupMainView, PopupGenerateView, TabImportView",
    "demo.controller": "कंट्रोलर:",
    "demo.controllerDesc": "React कंपोनेंट्स इवेंट्स को हैंडल करते हैं",
    "privacy.back": "वापस",
    "privacy.title": "गोपनीयता नीति",
    "privacy.subtitle": "PokeBit - उच्च एन्ट्रॉपी वॉलेट जेनरेटर. A child's game.",
    "privacy.lastUpdated": "अंतिम अपडेट:",
    "privacy.section1.title": "1. परिचय",
    "privacy.section1.text": "PokeBit एक ब्राउज़र एक्सटेंशन है जो सुरक्षित रूप से क्रिप्टोकरेंसी वॉलेट उत्पन्न और प्रबंधित करने के लिए डिज़ाइन किया गया है। यह गोपनीयता नीति बताती है कि हम आपके व्यक्तिगत डेटा को कैसे संभालते हैं (या बल्कि, कैसे नहीं संभालते)।",
    "privacy.section2.title": "2. जो डेटा हम एकत्र नहीं करते",
    "privacy.section2.text": "PokeBit पूर्ण गोपनीयता दृष्टिकोण के साथ डिज़ाइन किया गया है। हम कोई व्यक्तिगत डेटा एकत्र, संग्रहीत या प्रसारित नहीं करते। विशेष रूप से:",
    "privacy.section2.items": "हम सीड फ्रेज़ एकत्र नहीं करते|हम निजी कुंजियाँ एकत्र नहीं करते|हम वॉलेट पते एकत्र नहीं करते|हम एन्क्रिप्शन पासवर्ड एकत्र नहीं करते|हम उपयोग जानकारी या विश्लेषण एकत्र नहीं करते|हम IP पते एकत्र नहीं करते|हम डिवाइस जानकारी एकत्र नहीं करते|हम ट्रैकिंग कुकीज़ का उपयोग नहीं करते",
    "privacy.section3.title": "3. 100% स्थानीय प्रसंस्करण",
    "privacy.section3.text": "सभी PokeBit कार्यक्षमता विशेष रूप से आपके स्थानीय डिवाइस पर चलती है:",
    "privacy.section3.items": "वॉलेट जनरेशन: स्थानीय क्रिप्टोग्राफिक एन्ट्रॉपी का उपयोग करके सीड फ्रेज़ उत्पन्न होते हैं|कुंजी व्युत्पन्न: BIP-32/BIP-44/BIP-84 मानकों का उपयोग करके निजी और सार्वजनिक कुंजियाँ स्थानीय रूप से व्युत्पन्न होती हैं|एन्क्रिप्शन: .aes फ़ाइलें AES-256 के साथ स्थानीय रूप से एन्क्रिप्ट होती हैं|संग्रहण: डेटा तभी सहेजा जाता है जब आप अपने डिवाइस पर फ़ाइल निर्यात करना चुनते हैं",
    "privacy.section4.title": "4. कोई बाहरी कनेक्शन नहीं",
    "privacy.section4.text": "PokeBit बाहरी सर्वर से कोई कनेक्शन नहीं बनाता। एक बार इंस्टॉल होने के बाद एक्सटेंशन पूरी तरह ऑफ़लाइन काम करता है। कोई नहीं है:",
    "privacy.section4.items": "बैकएंड सर्वर|तृतीय-पक्ष APIs|विश्लेषण सेवाएं|विज्ञापन सेवाएं|क्लाउड सिंक्रनाइज़ेशन",
    "privacy.section5.title": "5. एक्सटेंशन अनुमतियाँ",
    "privacy.section5.text": "PokeBit को किसी विशेष ब्राउज़र अनुमतियों की आवश्यकता नहीं है। एक्सटेंशन पूरी तरह से अपने संदर्भ में संचालित होता है:",
    "privacy.section5.items": "आपके ब्राउज़िंग इतिहास तक कोई पहुंच नहीं|आपके टैब या विंडो तक कोई पहुंच नहीं|आपके व्यक्तिगत डेटा तक कोई पहुंच नहीं|भाषा और थीम प्राथमिकताएँ मानक ब्राउज़र स्टोरेज (localStorage) का उपयोग करके स्थानीय रूप से संग्रहीत होती हैं",
    "privacy.section6.title": "6. सुरक्षा",
    "privacy.section6.text": "आपकी क्रिप्टो संपत्तियों की सुरक्षा पूरी तरह आप पर निर्भर करती है:",
    "privacy.section6.items": "अपना सीड फ्रेज़ सुरक्षित ऑफ़लाइन स्थान पर रखें|अपनी .aes फ़ाइलों को एन्क्रिप्ट करने के लिए मजबूत पासवर्ड का उपयोग करें|अपना सीड फ्रेज़ या निजी कुंजियाँ कभी साझा न करें|हमेशा सत्यापित करें कि आप आधिकारिक एक्सटेंशन का उपयोग कर रहे हैं",
    "privacy.section7.title": "7. ओपन सोर्स",
    "privacy.section7.text": "PokeBit स्रोत कोड सार्वजनिक ऑडिट के लिए उपलब्ध है। आप कोड की समीक्षा करके व्यक्तिगत रूप से सत्यापित कर सकते हैं कि कोई डेटा संचरण नहीं है।",
    "privacy.section8.title": "8. इस नीति में परिवर्तन",
    "privacy.section8.text": "यदि हम इस गोपनीयता नीति में परिवर्तन करते हैं, तो हम इस पृष्ठ के शीर्ष पर 'अंतिम अपडेट' तिथि अपडेट करेंगे।",
    "privacy.section9.title": "9. संपर्क",
    "privacy.section9.text": "यदि आपके पास इस गोपनीयता नीति के बारे में प्रश्न हैं, तो आप हमसे संपर्क कर सकते हैं:",
    "privacy.summary": "सारांश: PokeBit कोई डेटा एकत्र, संग्रहीत या प्रसारित नहीं करता। सभी प्रसंस्करण आपके डिवाइस पर स्थानीय रूप से होता है। आपकी कुंजियाँ, आपकी क्रिप्टो।",
    "privacy.footer": "PokeBit | doctor.bitcoin | Cryptovault 2026",
  },
  ru: {
    "app.title": "PokeBit",
    "app.subtitle": "A child's game.",
    "main.generate": "СОЗДАТЬ НОВОЕ ХРАНИЛИЩЕ",
    "main.generate12": "СОЗДАТЬ ХРАНИЛИЩЕ (12 СЛОВ)",
    "main.generate24": "СОЗДАТЬ ХРАНИЛИЩЕ (24 СЛОВА)",
    "main.import": "ИМПОРТИРОВАТЬ ХРАНИЛИЩЕ",
    "main.securityTitle": "Локальная безопасность",
    "main.securityText": "Все ключи генерируются локально на вашем устройстве. Они никогда не отправляются на внешние серверы.",
    "main.footer": "©2026 PokeBit  •  Designed by doctor.bitcoin  •  A child's game.",
    "main.privacyLink": "Политика конфиденциальности",
    "main.downloadExtension": "Скачать расширение Chrome",
    "generate.title": "🔐 Хранилище создано",
    "generate.subtitle": "Ваша сид-фраза и производные ключи",
    "generate.derivedAccounts": "🛡️ Производные аккаунты",
    "generate.protectVault": "🔒 Защитить хранилище",
    "generate.howItWorks": "Как это работает?",
    "generate.helpTitle": "Шифрование военного уровня",
    "generate.helpText": "Используя нашу технологию шифрования военного уровня (AES-256), информация о ваших кошельках будет защищена паролем в легко экспортируемом файле.\n\nМы рекомендуем прикрепить файл к электронному письму вместе с другими файлами (эффект смешивания) и отправить его себе или другим. Таким образом, информация о ваших кошельках будет в облаке, доступная просто через доступ к электронной почте или попросив отправителя переслать письмо с вложениями.\n\nТаким образом, вы никогда не потеряете доступ к своим кошелькам, обеспечивая высокий уровень безопасности.",
    "generate.helpWarning": "Примечание: Мы не несем ответственности за утерянные пароли. Без пароля доступ к зашифрованной информации кошелька невозможен.",
    "generate.passwordPlaceholder": "Пароль (мин. 8 символов)",
    "generate.repeatPassword": "Повторите пароль",
    "generate.exportVault": "Экспортировать хранилище (.aes)",
    "generate.generateNew": "Создать новое",
    "generate.words": "слов",
    "generate.back": "Вернуться на главную",
    "generate.loading": "Создание хранилища",
    "generate.loadingMsg": "Генерация с высокой энтропией",
    "generate.success": "Хранилище успешно создано",
    "generate.exported": "Зашифрованный файл успешно экспортирован",
    "generate.errorPassword": "Вы должны ввести пароль",
    "generate.errorPasswordLength": "Пароль должен содержать не менее 8 символов",
    "generate.errorConfirm": "Вы должны подтвердить пароль",
    "generate.errorMatch": "Пароли не совпадают",
    "import.title": "Импортировать хранилище",
    "import.subtitle": "Восстановите кошелек из зашифрованного файла",
    "import.fileLabel": "📁 Файл хранилища",
    "import.dragHere": "Перетащите файл сюда",
    "import.clickSelect": "или нажмите для выбора",
    "import.onlyAes": "Только файлы .aes",
    "import.passwordLabel": "🔒 Пароль расшифровки",
    "import.passwordPlaceholder": "Введите пароль хранилища...",
    "import.importButton": "ИМПОРТИРОВАТЬ ХРАНИЛИЩЕ",
    "import.importing": "Расшифровка...",
    "import.success": "Хранилище успешно расшифровано",
    "import.successMsg": "Ваш кошелек восстановлен",
    "import.back": "Вернуться к попапу",
    "import.errorFile": "Вы должны выбрать файл хранилища",
    "import.errorPassword": "Вы должны ввести пароль",
    "import.errorPasswordLength": "Пароль должен содержать не менее 8 символов",
    "import.errorFormat": "Файл должен иметь расширение .aes",
    "import.errorInvalid": "Недействительный файл или неверный пароль",
    "import.reset": "Сброс",
    "import.resetTitle": "Подтвердите сброс",
    "import.resetFinalTitle": "Окончательное подтверждение",
    "import.resetWarning1": "Вы уверены, что хотите сбросить? Это удалит текущий кошелек из этого представления.",
    "import.resetWarning2": "Это ваше ПОСЛЕДНЕЕ ПРЕДУПРЕЖДЕНИЕ. Информация о кошельке будет удалена из этого сеанса. Убедитесь, что вы экспортировали хранилище, если это необходимо.",
    "import.resetSuccess": "Кошелек успешно сброшен",
    "import.cancel": "Отмена",
    "import.continue": "Продолжить",
    "import.confirmReset": "Да, сбросить",
    "import.backMenu": "Вернуться в меню",
    "import.exportNewPassword": "Экспорт с новым паролем",
    "import.newPassword": "Новый пароль",
    "import.repeatNewPassword": "Повторите новый пароль",
    "import.exportButton": "Экспортировать хранилище",
    "password.weak": "Слабый пароль",
    "password.medium": "Средний пароль",
    "password.strong": "Сильный пароль",
    "seedPhrase.title": "🌱 Фраза восстановления",
    "seedPhrase.warning": "Никогда не делитесь этой фразой. Любой, кто имеет к ней доступ, может украсть ваши средства.",
    "seedPhrase.copied": "Сид-фраза скопирована!",
    "crypto.privateKey": "Приватный ключ",
    "crypto.publicAddress": "Публичный адрес",
    "crypto.copied": "Скопировано!",
    "bip39.question": "Что такое BIP-39?",
    "bip39.title": "Стандарт BIP-39",
    "bip39.paragraph1": "Словарь BIP-39 состоит из 2048 английских слов, тщательно подобранных так, чтобы первые 4 символа уникально идентифицировали каждое слово (нет двух слов с одинаковыми первыми 4 буквами), и избегались слова, звучащие одинаково фонетически, даже если они пишутся по-разному. Кроме того, минимальная длина слова составляет 3 буквы. Каждое слово в словаре закодировано 11 битами.",
    "bip39.paragraph2": "Наша система генерации фраз предлагает уникальную систему высокой энтропии, в которой вероятность того, что каждое слово займет позицию во фразе, равномерна и равна 1/2048.",
    "bip39.note": "Всегда помните девиз: Ваши ключи, Ваши криптовалюты.",
    "derivation.question": "Что это?",
    "derivation.title": "Процесс получения ключей",
    "derivation.paragraph1": "Иерархическое детерминированное (HD) получение позволяет генерировать несколько пар ключей из одной seed-фразы. Используя стандарты BIP-32/BIP-44/BIP-84, мастер-ключ получается из мнемоники с помощью PBKDF2 с 2048 итерациями.",
    "derivation.paragraph2": "Из мастер-ключа получаются дочерние ключи по определенным путям. Для Ethereum мы используем m/44'/60'/0'/0/0, для Bitcoin m/84'/0'/0'/0/0 (нативный SegWit). Приватный ключ — это 256-битное случайное число, служащее 'секретом' для подписи транзакций.",
    "derivation.paragraph3": "Публичный адрес получается из приватного ключа с использованием криптографии эллиптических кривых (secp256k1). Для Ethereum применяется хеш Keccak-256 к публичному ключу. Для Bitcoin применяются хеши SHA-256 и RIPEMD-160, затем кодирование Bech32 для получения адреса bc1q...",
    "derivation.note": "Этот односторонний процесс гарантирует невозможность получения приватного ключа из публичного адреса.",
    "importInfo.question": "Как это работает?",
    "importInfo.title": "Система импорта/экспорта",
    "importInfo.paragraph1": "Наша система выполняет тройную функцию: генерация, экспорт и импорт кошельков с очень специальным форматом, разработанным в наших лабораториях.",
    "importInfo.paragraph2": "Требования для правильного импорта кошелька: помнить пароль шифрования и выполнить шифрование (экспорт) из нашего приложения.",
    "importInfo.note": "Файл будет иметь расширение .aes, и имя файла не имеет значения для процесса расшифровки, поэтому вы можете настроить имя файла по своему усмотрению.",
    "demo.badge": "Макет расширения Chrome",
    "demo.title": "PokeBit Расширение",
    "demo.subtitle": "Предпросмотр: Начальный попап → Генерация (попап) → Импорт (новая вкладка)",
    "demo.popupSize": "Попап: 420px",
    "demo.viewTab": "Полноэкранный вид",
    "demo.architecture": "📐 Архитектура MVC",
    "demo.model": "Модель:",
    "demo.modelDesc": "src/lib/model.ts - Логика генерации и деривации",
    "demo.views": "Представления:",
    "demo.viewsDesc": "src/views/ - PopupMainView, PopupGenerateView, TabImportView",
    "demo.controller": "Контроллер:",
    "demo.controllerDesc": "React компоненты обрабатывают события",
    "privacy.back": "Назад",
    "privacy.title": "Политика конфиденциальности",
    "privacy.subtitle": "PokeBit - Генератор кошельков высокой энтропии. A child's game.",
    "privacy.lastUpdated": "Последнее обновление:",
    "privacy.section1.title": "1. Введение",
    "privacy.section1.text": "PokeBit — это расширение браузера, предназначенное для безопасной генерации и управления криптовалютными кошельками. Эта политика конфиденциальности объясняет, как мы обрабатываем (или, точнее, как мы НЕ обрабатываем) ваши персональные данные.",
    "privacy.section2.title": "2. Данные, которые мы НЕ собираем",
    "privacy.section2.text": "PokeBit разработан с подходом полной конфиденциальности. Мы не собираем, не храним и не передаем никакие персональные данные. В частности:",
    "privacy.section2.items": "Мы не собираем сид-фразы|Мы не собираем приватные ключи|Мы не собираем адреса кошельков|Мы не собираем пароли шифрования|Мы не собираем информацию об использовании или аналитику|Мы не собираем IP-адреса|Мы не собираем информацию об устройстве|Мы не используем отслеживающие куки",
    "privacy.section3.title": "3. 100% локальная обработка",
    "privacy.section3.text": "Вся функциональность PokeBit выполняется исключительно на вашем локальном устройстве:",
    "privacy.section3.items": "Генерация кошелька: Сид-фразы генерируются с использованием локальной криптографической энтропии|Получение ключей: Приватные и публичные ключи получаются локально с использованием стандартов BIP-32/BIP-44/BIP-84|Шифрование: Файлы .aes шифруются локально с помощью AES-256|Хранение: Данные сохраняются только если вы решите экспортировать файл на свое устройство",
    "privacy.section4.title": "4. Нет внешних подключений",
    "privacy.section4.text": "PokeBit не устанавливает никаких подключений к внешним серверам. Расширение работает полностью офлайн после установки. Нет:",
    "privacy.section4.items": "Бэкенд-серверов|Сторонних API|Сервисов аналитики|Рекламных сервисов|Облачной синхронизации",
    "privacy.section5.title": "5. Разрешения расширения",
    "privacy.section5.text": "PokeBit НЕ требует специальных разрешений браузера. Расширение работает полностью в своем собственном контексте:",
    "privacy.section5.items": "Нет доступа к истории просмотров|Нет доступа к вкладкам или окнам|Нет доступа к личным данным|Настройки языка и темы сохраняются локально с использованием стандартного хранилища браузера (localStorage)",
    "privacy.section6.title": "6. Безопасность",
    "privacy.section6.text": "Безопасность ваших криптоактивов зависит исключительно от вас:",
    "privacy.section6.items": "Храните сид-фразу в безопасном офлайн-месте|Используйте надежные пароли для шифрования файлов .aes|Никогда не делитесь сид-фразой или приватными ключами|Всегда проверяйте, что используете официальное расширение",
    "privacy.section7.title": "7. Открытый исходный код",
    "privacy.section7.text": "Исходный код PokeBit доступен для публичного аудита. Вы можете лично убедиться в отсутствии передачи данных, просмотрев код.",
    "privacy.section8.title": "8. Изменения политики",
    "privacy.section8.text": "Если мы внесем изменения в эту политику конфиденциальности, мы обновим дату 'последнего обновления' в верхней части этой страницы.",
    "privacy.section9.title": "9. Контакты",
    "privacy.section9.text": "Если у вас есть вопросы об этой политике конфиденциальности, вы можете связаться с нами:",
    "privacy.summary": "Резюме: PokeBit не собирает, не хранит и не передает никаких данных. Вся обработка происходит локально на вашем устройстве. Ваши ключи, ваши криптовалюты.",
    "privacy.footer": "PokeBit | doctor.bitcoin | Cryptovault 2026",
  },
  ar: {
    "app.title": "PokeBit",
    "app.subtitle": "A child's game.",
    "main.generate": "إنشاء خزنة جديدة",
    "main.generate12": "إنشاء خزنة (12 كلمة)",
    "main.generate24": "إنشاء خزنة (24 كلمة)",
    "main.import": "استيراد خزنة",
    "main.securityTitle": "الأمان المحلي",
    "main.securityText": "جميع المفاتيح تُنشأ محلياً على جهازك. لا يتم إرسالها أبداً إلى خوادم خارجية.",
    "main.footer": "©2026 PokeBit  •  Designed by doctor.bitcoin  •  A child's game.",
    "main.privacyLink": "سياسة الخصوصية",
    "main.downloadExtension": "تحميل إضافة Chrome",
    "generate.title": "🔐 تم إنشاء الخزنة",
    "generate.subtitle": "عبارة البذور ومفاتيحك المشتقة",
    "generate.derivedAccounts": "🛡️ الحسابات المشتقة",
    "generate.protectVault": "🔒 حماية الخزنة",
    "generate.howItWorks": "كيف يعمل؟",
    "generate.helpTitle": "تشفير بمستوى عسكري",
    "generate.helpText": "باستخدام تقنية التشفير العسكرية (AES-256)، ستكون معلومات محفظتك محمية بكلمة مرورك في ملف قابل للتصدير بسهولة.\n\nنوصي بإرفاق الملف في بريد إلكتروني مع ملفات أخرى (تأثير الخلط) وإرساله لنفسك أو للآخرين. بهذه الطريقة، ستكون معلومات محافظك في السحابة، متاحة ببساطة عن طريق الوصول إلى بريدك الإلكتروني.\n\nبهذه الطريقة، لن تفقد أبداً الوصول إلى محافظك مع ضمان مستوى عالٍ من الأمان.",
    "generate.helpWarning": "ملاحظة: نحن غير مسؤولين عن كلمات المرور المفقودة. بدون كلمة المرور، لا يمكن الوصول إلى معلومات المحفظة المشفرة.",
    "generate.passwordPlaceholder": "كلمة المرور (8 أحرف كحد أدنى)",
    "generate.repeatPassword": "تكرار كلمة المرور",
    "generate.exportVault": "تصدير الخزنة (.aes)",
    "generate.generateNew": "إنشاء جديدة",
    "generate.words": "كلمات",
    "generate.back": "العودة للرئيسية",
    "generate.loading": "جاري إنشاء الخزنة",
    "generate.loadingMsg": "توليد عالي الإنتروبيا",
    "generate.success": "تم إنشاء الخزنة بنجاح",
    "generate.exported": "تم تصدير الملف المشفر بنجاح",
    "generate.errorPassword": "يجب إدخال كلمة مرور",
    "generate.errorPasswordLength": "يجب أن تكون كلمة المرور 8 أحرف على الأقل",
    "generate.errorConfirm": "يجب تأكيد كلمة المرور",
    "generate.errorMatch": "كلمات المرور غير متطابقة",
    "import.title": "استيراد خزنة",
    "import.subtitle": "استعادة محفظتك من ملف مشفر",
    "import.fileLabel": "📁 ملف الخزنة",
    "import.dragHere": "اسحب ملفك هنا",
    "import.clickSelect": "أو انقر للاختيار",
    "import.onlyAes": "ملفات .aes فقط",
    "import.passwordLabel": "🔒 كلمة مرور فك التشفير",
    "import.passwordPlaceholder": "أدخل كلمة مرور الخزنة...",
    "import.importButton": "استيراد الخزنة",
    "import.importing": "جاري فك التشفير...",
    "import.success": "تم فك تشفير الخزنة بنجاح",
    "import.successMsg": "تم استعادة محفظتك",
    "import.back": "العودة للنافذة المنبثقة",
    "import.errorFile": "يجب اختيار ملف خزنة",
    "import.errorPassword": "يجب إدخال كلمة المرور",
    "import.errorPasswordLength": "يجب أن تكون كلمة المرور 8 أحرف على الأقل",
    "import.errorFormat": "يجب أن يكون الملف بامتداد .aes",
    "import.errorInvalid": "ملف غير صالح أو كلمة مرور خاطئة",
    "import.reset": "إعادة تعيين",
    "import.resetTitle": "تأكيد إعادة التعيين",
    "import.resetFinalTitle": "التأكيد النهائي",
    "import.resetWarning1": "هل أنت متأكد من إعادة التعيين؟ سيؤدي ذلك إلى مسح المحفظة الحالية من هذا العرض.",
    "import.resetWarning2": "هذا هو تحذيرك الأخير. سيتم مسح معلومات المحفظة من هذه الجلسة. تأكد من تصدير الخزنة إذا لزم الأمر.",
    "import.resetSuccess": "تم إعادة تعيين المحفظة بنجاح",
    "import.cancel": "إلغاء",
    "import.continue": "متابعة",
    "import.confirmReset": "نعم، إعادة تعيين",
    "import.backMenu": "العودة للقائمة",
    "import.exportNewPassword": "تصدير بكلمة مرور جديدة",
    "import.newPassword": "كلمة مرور جديدة",
    "import.repeatNewPassword": "تكرار كلمة المرور الجديدة",
    "import.exportButton": "تصدير الخزنة",
    "password.weak": "كلمة مرور ضعيفة",
    "password.medium": "كلمة مرور متوسطة",
    "password.strong": "كلمة مرور قوية",
    "seedPhrase.title": "🌱 عبارة الاسترداد",
    "seedPhrase.warning": "لا تشارك هذه العبارة أبداً. أي شخص يمكنه الوصول إليها يمكنه سرقة أموالك.",
    "seedPhrase.copied": "تم نسخ عبارة البذور!",
    "crypto.privateKey": "المفتاح الخاص",
    "crypto.publicAddress": "العنوان العام",
    "crypto.copied": "تم النسخ!",
    "bip39.question": "ما هو BIP-39؟",
    "bip39.title": "معيار BIP-39",
    "bip39.paragraph1": "يتكون قاموس BIP-39 من 2048 كلمة إنجليزية، تم اختيارها بعناية بحيث تحدد الأحرف الأربعة الأولى كل كلمة بشكل فريد (لا توجد كلمتان تشتركان في نفس الأحرف الأربعة الأولى) ويتم تجنب الكلمات التي تبدو متشابهة صوتياً. الحد الأدنى لطول الكلمة هو 3 أحرف. كل كلمة مشفرة بـ 11 بت.",
    "bip39.paragraph2": "يقدم نظام توليد العبارات لدينا نظاماً فريداً عالي الإنتروبيا حيث احتمال أن تشغل كل كلمة موقعاً في العبارة موحد ويساوي 1/2048.",
    "bip39.note": "تذكر دائماً الشعار: مفاتيحك، عملاتك المشفرة.",
    "derivation.question": "ما هذا؟",
    "derivation.title": "عملية اشتقاق المفاتيح",
    "derivation.paragraph1": "يسمح الاشتقاق الهرمي المحدد (HD) بتوليد أزواج مفاتيح متعددة من عبارة بذور واحدة. باستخدام معايير BIP-32/BIP-44/BIP-84، يتم اشتقاق مفتاح رئيسي من العبارة باستخدام PBKDF2 مع 2048 تكراراً.",
    "derivation.paragraph2": "من المفتاح الرئيسي، يتم اشتقاق مفاتيح فرعية باتباع مسارات محددة. لإيثريوم نستخدم m/44'/60'/0'/0/0 ولبيتكوين m/84'/0'/0'/0/0 (SegWit الأصلي). المفتاح الخاص هو رقم عشوائي 256 بت يعمل كـ 'سر' لتوقيع المعاملات.",
    "derivation.paragraph3": "يتم اشتقاق العنوان العام من المفتاح الخاص باستخدام تشفير المنحنى الإهليلجي (secp256k1). لإيثريوم، يتم تطبيق تجزئة Keccak-256 على المفتاح العام. لبيتكوين، يتم تطبيق تجزئات SHA-256 وRIPEMD-160، يليها ترميز Bech32 للحصول على عنوان bc1q...",
    "derivation.note": "تضمن هذه العملية أحادية الاتجاه استحالة الحصول على المفتاح الخاص من العنوان العام.",
    "importInfo.question": "كيف يعمل؟",
    "importInfo.title": "نظام الاستيراد/التصدير",
    "importInfo.paragraph1": "يؤدي نظامنا وظيفة ثلاثية لتوليد المحفظة والتصدير والاستيراد بتنسيق خاص جداً صُمم في مختبراتنا.",
    "importInfo.paragraph2": "متطلبات إجراء استيراد صحيح للمحفظة اثنان: تذكر كلمة مرور التشفير وإجراء التشفير (التصدير) من تطبيقنا.",
    "importInfo.note": "سيكون للملف امتداد .aes واسم الملف غير مهم لعملية فك التشفير، لذا يمكنك تخصيص اسم الملف حسب رغبتك.",
    "demo.badge": "نموذج إضافة Chrome",
    "demo.title": "إضافة PokeBit",
    "demo.subtitle": "معاينة التدفق: النافذة المنبثقة الأولية ← عرض التوليد (منبثقة) ← عرض الاستيراد (تبويب جديد)",
    "demo.popupSize": "عرض النافذة المنبثقة: 420px",
    "demo.viewTab": "عرض التبويب الكامل",
    "demo.architecture": "📐 هندسة MVC",
    "demo.model": "النموذج:",
    "demo.modelDesc": "src/lib/model.ts - منطق التوليد والاشتقاق",
    "demo.views": "العروض:",
    "demo.viewsDesc": "src/views/ - PopupMainView, PopupGenerateView, TabImportView",
    "demo.controller": "المتحكم:",
    "demo.controllerDesc": "مكونات React تتعامل مع الأحداث",
    "privacy.back": "رجوع",
    "privacy.title": "سياسة الخصوصية",
    "privacy.subtitle": "PokeBit - مولد محافظ عالي الإنتروبيا. A child's game.",
    "privacy.lastUpdated": "آخر تحديث:",
    "privacy.section1.title": "1. المقدمة",
    "privacy.section1.text": "PokeBit هي إضافة متصفح مصممة لتوليد وإدارة محافظ العملات المشفرة بشكل آمن. توضح سياسة الخصوصية هذه كيف نتعامل (أو بالأحرى، كيف لا نتعامل) مع بياناتك الشخصية.",
    "privacy.section2.title": "2. البيانات التي لا نجمعها",
    "privacy.section2.text": "تم تصميم PokeBit بنهج الخصوصية الكاملة. نحن لا نجمع أو نخزن أو ننقل أي بيانات شخصية. تحديداً:",
    "privacy.section2.items": "لا نجمع عبارات البذور|لا نجمع المفاتيح الخاصة|لا نجمع عناوين المحافظ|لا نجمع كلمات مرور التشفير|لا نجمع معلومات الاستخدام أو التحليلات|لا نجمع عناوين IP|لا نجمع معلومات الجهاز|لا نستخدم ملفات تعريف الارتباط للتتبع",
    "privacy.section3.title": "3. معالجة محلية 100%",
    "privacy.section3.text": "تعمل جميع وظائف PokeBit حصرياً على جهازك المحلي:",
    "privacy.section3.items": "توليد المحفظة: يتم إنشاء عبارات البذور باستخدام إنتروبيا تشفيرية محلية|اشتقاق المفاتيح: يتم اشتقاق المفاتيح الخاصة والعامة محلياً باستخدام معايير BIP-32/BIP-44/BIP-84|التشفير: يتم تشفير ملفات .aes محلياً باستخدام AES-256|التخزين: يتم حفظ البيانات فقط إذا اخترت تصدير ملف إلى جهازك",
    "privacy.section4.title": "4. لا اتصالات خارجية",
    "privacy.section4.text": "لا يقوم PokeBit بأي اتصالات بخوادم خارجية. تعمل الإضافة بشكل كامل دون اتصال بعد التثبيت. لا يوجد:",
    "privacy.section4.items": "خوادم خلفية|واجهات برمجة تطبيقات تابعة لجهات خارجية|خدمات تحليلات|خدمات إعلانية|مزامنة سحابية",
    "privacy.section5.title": "5. أذونات الإضافة",
    "privacy.section5.text": "لا يتطلب PokeBit أي أذونات متصفح خاصة. تعمل الإضافة بالكامل ضمن سياقها الخاص:",
    "privacy.section5.items": "لا وصول إلى سجل التصفح|لا وصول إلى علامات التبويب أو النوافذ|لا وصول إلى بياناتك الشخصية|يتم تخزين تفضيلات اللغة والسمة محلياً باستخدام التخزين القياسي للمتصفح (localStorage)",
    "privacy.section6.title": "6. الأمان",
    "privacy.section6.text": "يعتمد أمان أصولك المشفرة عليك بالكامل:",
    "privacy.section6.items": "احتفظ بعبارة البذور في مكان آمن غير متصل بالإنترنت|استخدم كلمات مرور قوية لتشفير ملفات .aes|لا تشارك أبداً عبارة البذور أو المفاتيح الخاصة|تحقق دائماً من أنك تستخدم الإضافة الرسمية",
    "privacy.section7.title": "7. المصدر المفتوح",
    "privacy.section7.text": "الكود المصدري لـ PokeBit متاح للتدقيق العام. يمكنك التحقق شخصياً من عدم وجود أي نقل للبيانات من خلال مراجعة الكود.",
    "privacy.section8.title": "8. التغييرات على هذه السياسة",
    "privacy.section8.text": "إذا أجرينا تغييرات على سياسة الخصوصية هذه، سنقوم بتحديث تاريخ 'آخر تحديث' أعلى هذه الصفحة.",
    "privacy.section9.title": "9. الاتصال",
    "privacy.section9.text": "إذا كانت لديك أسئلة حول سياسة الخصوصية هذه، يمكنك الاتصال بنا على:",
    "privacy.summary": "ملخص: لا يجمع PokeBit أو يخزن أو ينقل أي بيانات. تتم جميع المعالجة محلياً على جهازك. مفاتيحك، عملاتك المشفرة.",
    "privacy.footer": "PokeBit | doctor.bitcoin | Cryptovault 2026",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const RTL_LANGUAGES: Language[] = ["ar"];

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("pokebit-language");
    return (saved as Language) || "en";
  });

  const isRTL = RTL_LANGUAGES.includes(language);

  // Apply RTL direction to document
  useEffect(() => {
    document.documentElement.dir = isRTL ? "rtl" : "ltr";
    document.documentElement.lang = language;
  }, [language, isRTL]);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem("pokebit-language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
