import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "es" | "zh" | "hi" | "ru";

interface LanguageInfo {
  code: Language;
  name: string;
  flag: string;
}

export const languages: LanguageInfo[] = [
  { code: "en", name: "English", flag: "🇺🇸" },
  { code: "es", name: "Español", flag: "🇪🇸" },
  { code: "zh", name: "中文", flag: "🇨🇳" },
  { code: "hi", name: "हिन्दी", flag: "🇮🇳" },
  { code: "ru", name: "Русский", flag: "🇷🇺" },
];

const translations: Record<Language, Record<string, string>> = {
  en: {
    "app.title": "PokeBit",
    "app.subtitle": "High Entropy Wallet Generator",
    "main.generate": "GENERATE NEW VAULT",
    "main.generate12": "GENERATE VAULT (12 WORDS)",
    "main.generate24": "GENERATE VAULT (24 WORDS)",
    "main.import": "IMPORT VAULT",
    "main.securityTitle": "Local Security",
    "main.securityText": "All keys are generated locally on your device. They are never sent to external servers.",
    "main.footer": "PokeBit  |  doctor.bitcoin  |  Cryptovault 2026",
    "generate.title": "🔐 Vault Generated",
    "generate.subtitle": "Your seed phrase and derived keys",
    "generate.derivedAccounts": "🛡️ Derived Accounts",
    "generate.protectVault": "🔒 Protect Vault",
    "generate.howItWorks": "How does it work?",
    "generate.helpTitle": "Military Grade Encryption",
    "generate.helpText": "Using our military-grade encryption technology (AES-256), your wallet information will be protected by your password in an easily exportable file.\n\nWe recommend attaching the file to an email along with other files (mixing effect) and sending it to yourself or others. This way, you'll have your wallet information in the cloud, accessible simply by accessing your email or asking the person who sent you the email to resend it with the attachments.\n\nThis way, you'll never lose access to your wallets while ensuring a high level of security.",
    "generate.helpWarning": "Note: We are not responsible for lost passwords. Without the password, the encrypted wallet information cannot be accessed.",
    "generate.passwordPlaceholder": "Password (min. 8 characters)",
    "generate.repeatPassword": "Repeat password",
    "generate.exportVault": "Export Vault (.aes)",
    "generate.generateNew": "Generate New",
    "generate.words": "words",
    "generate.back": "Back to Home",
    "generate.loading": "Generating Vault",
    "generate.loadingMsg": "High Entropy Generation",
    "generate.success": "Vault generated successfully",
    "generate.exported": "Encrypted file exported successfully",
    "generate.errorPassword": "You must enter a password",
    "generate.errorPasswordLength": "Password must be at least 8 characters",
    "generate.errorConfirm": "You must confirm the password",
    "generate.errorMatch": "Passwords do not match",
    "import.title": "Import Vault",
    "import.subtitle": "Restore your wallet from an encrypted file",
    "import.fileLabel": "📁 Vault File",
    "import.dragHere": "Drag your file here",
    "import.clickSelect": "or click to select",
    "import.onlyAes": "Only .aes files",
    "import.passwordLabel": "🔒 Decryption Password",
    "import.passwordPlaceholder": "Enter the vault password...",
    "import.importButton": "IMPORT VAULT",
    "import.importing": "Decrypting...",
    "import.success": "Vault decrypted successfully",
    "import.successMsg": "Your wallet has been restored",
    "import.back": "Back to Popup",
    "import.errorFile": "You must select a vault file",
    "import.errorPassword": "You must enter the password",
    "import.errorPasswordLength": "Password must be at least 8 characters",
    "import.errorFormat": "File must have .aes extension",
    "import.errorInvalid": "Invalid file or incorrect password",
    "import.reset": "Reset",
    "import.resetTitle": "Confirm Reset",
    "import.resetFinalTitle": "Final Confirmation",
    "import.resetWarning1": "Are you sure you want to reset? This will clear the current wallet from this view.",
    "import.resetWarning2": "This is your LAST WARNING. The wallet information will be cleared from this session. Make sure you have exported the vault if needed.",
    "import.resetSuccess": "Wallet reset successfully",
    "import.cancel": "Cancel",
    "import.continue": "Continue",
    "import.confirmReset": "Yes, Reset",
    "import.backMenu": "Back to Menu",
    "import.exportNewPassword": "Export with New Password",
    "import.newPassword": "New password",
    "import.repeatNewPassword": "Repeat new password",
    "import.exportButton": "Export Vault",
    "password.weak": "Weak password",
    "password.medium": "Medium password",
    "password.strong": "Strong password",
    "seedPhrase.title": "🌱 Recovery Phrase",
    "seedPhrase.warning": "Never share this phrase. Anyone with access can steal your funds.",
    "seedPhrase.copied": "Seed phrase copied!",
    "crypto.privateKey": "Private Key",
    "crypto.publicAddress": "Public Address",
    "crypto.copied": "Copied!",
    "bip39.question": "What is BIP-39?",
    "bip39.title": "BIP-39 Standard",
    "bip39.paragraph1": "The BIP-39 dictionary consists of 2048 English words, carefully chosen to respect the rule that the first 4 characters uniquely identify each word (no two words share the same first 4 letters) and to avoid using words that sound the same phonetically even if spelled differently. Additionally, the minimum word length is 3 letters. Each word in the dictionary is encoded with 11 bits.",
    "bip39.paragraph2": "Our phrase generation system offers a unique high-entropy system in which the probability of each word occupying a position within the phrase is uniform and equal to 1/2048.",
    "bip39.note": "Remember always the motto: Your keys, Your Cryptos.",
    "demo.badge": "Chrome Extension Mockup",
    "demo.title": "PokeBit Extension",
    "demo.subtitle": "Flow preview: Initial Popup → Generation View (popup) → Import View (new tab)",
    "demo.popupSize": "Popup View: 420px",
    "demo.viewTab": "View Full Tab View",
    "demo.architecture": "📐 MVC Architecture",
    "demo.model": "Model:",
    "demo.modelDesc": "src/lib/model.ts - Generation and derivation logic",
    "demo.views": "Views:",
    "demo.viewsDesc": "src/views/ - PopupMainView, PopupGenerateView, TabImportView",
    "demo.controller": "Controller:",
    "demo.controllerDesc": "React components handle events",
  },
  es: {
    "app.title": "PokeBit",
    "app.subtitle": "Generador de Wallets de Alta Entropía",
    "main.generate": "GENERAR NUEVA BÓVEDA",
    "main.generate12": "GENERAR BÓVEDA (12 PALABRAS)",
    "main.generate24": "GENERAR BÓVEDA (24 PALABRAS)",
    "main.import": "IMPORTAR BÓVEDA",
    "main.securityTitle": "Seguridad Local",
    "main.securityText": "Todas las claves se generan localmente en tu dispositivo. Nunca se envían a servidores externos.",
    "main.footer": "PokeBit  |  doctor.bitcoin  |  Cryptovault 2026",
    "generate.title": "🔐 Bóveda Generada",
    "generate.subtitle": "Tu frase semilla y claves derivadas",
    "generate.derivedAccounts": "🛡️ Cuentas Derivadas",
    "generate.protectVault": "🔒 Proteger Bóveda",
    "generate.howItWorks": "¿Cómo funciona?",
    "generate.helpTitle": "Encriptación de Grado Militar",
    "generate.helpText": "Utilizando nuestra tecnología de encriptación de grado militar (AES-256) la información de sus billeteras estará protegida por su contraseña en un fichero fácilmente exportable.\n\nLe recomendamos que utilice el fichero para adjuntarlo en algún email junto a otros ficheros (efecto mezcla) y enviárselo a usted mismo u otras personas. De esta forma tendrá la información de sus billeteras en la nube disponible con tan solo acceder a su email o pedir a la persona que le envió el email que se lo reenvíe junto a los ficheros adjuntos.\n\nDe esta forma nunca perderá el acceso a sus billeteras asegurando al mismo tiempo un alto nivel de seguridad.",
    "generate.helpWarning": "Nota: No nos hacemos responsables de la pérdida de la contraseña. Sin la contraseña no se podrá acceder a la información de la billetera encriptada.",
    "generate.passwordPlaceholder": "Contraseña (mín. 8 caracteres)",
    "generate.repeatPassword": "Repetir contraseña",
    "generate.exportVault": "Exportar Bóveda (.aes)",
    "generate.generateNew": "Generar Nueva",
    "generate.words": "palabras",
    "generate.back": "Volver al Inicio",
    "generate.loading": "Generando Bóveda",
    "generate.loadingMsg": "Generación de Alta Entropía",
    "generate.success": "Bóveda generada exitosamente",
    "generate.exported": "Archivo encriptado exportado correctamente",
    "generate.errorPassword": "Debes introducir una contraseña",
    "generate.errorPasswordLength": "La contraseña debe tener al menos 8 caracteres",
    "generate.errorConfirm": "Debes confirmar la contraseña",
    "generate.errorMatch": "Las contraseñas no coinciden",
    "import.title": "Importar Bóveda",
    "import.subtitle": "Restaura tu wallet desde un archivo encriptado",
    "import.fileLabel": "📁 Archivo de Bóveda",
    "import.dragHere": "Arrastra tu archivo aquí",
    "import.clickSelect": "o haz clic para seleccionar",
    "import.onlyAes": "Solo archivos .aes",
    "import.passwordLabel": "🔒 Contraseña de Descifrado",
    "import.passwordPlaceholder": "Introduce la contraseña de la bóveda...",
    "import.importButton": "IMPORTAR BÓVEDA",
    "import.importing": "Descifrando...",
    "import.success": "Bóveda descifrada correctamente",
    "import.successMsg": "Tu wallet ha sido restaurada",
    "import.back": "Volver al Popup",
    "import.errorFile": "Debes seleccionar un archivo de bóveda",
    "import.errorPassword": "Debes introducir la contraseña",
    "import.errorPasswordLength": "La contraseña debe tener al menos 8 caracteres",
    "import.errorFormat": "El archivo debe tener extensión .aes",
    "import.errorInvalid": "Archivo inválido o contraseña incorrecta",
    "import.reset": "Reiniciar",
    "import.resetTitle": "Confirmar Reinicio",
    "import.resetFinalTitle": "Confirmación Final",
    "import.resetWarning1": "¿Estás seguro de que quieres reiniciar? Esto borrará la wallet actual de esta vista.",
    "import.resetWarning2": "Esta es tu ÚLTIMA ADVERTENCIA. La información de la wallet será borrada de esta sesión. Asegúrate de haber exportado la bóveda si es necesario.",
    "import.resetSuccess": "Wallet reiniciada correctamente",
    "import.cancel": "Cancelar",
    "import.continue": "Continuar",
    "import.confirmReset": "Sí, Reiniciar",
    "import.backMenu": "Volver al Menú",
    "import.exportNewPassword": "Exportar con Nueva Contraseña",
    "import.newPassword": "Nueva contraseña",
    "import.repeatNewPassword": "Repetir nueva contraseña",
    "import.exportButton": "Exportar Bóveda",
    "password.weak": "Contraseña débil",
    "password.medium": "Contraseña media",
    "password.strong": "Contraseña fuerte",
    "seedPhrase.title": "🌱 Frase de Recuperación",
    "seedPhrase.warning": "Nunca compartas esta frase. Cualquiera con acceso puede robar tus fondos.",
    "seedPhrase.copied": "¡Frase semilla copiada!",
    "crypto.privateKey": "Clave Privada",
    "crypto.publicAddress": "Dirección Pública",
    "crypto.copied": "¡Copiado!",
    "bip39.question": "¿Qué es BIP-39?",
    "bip39.title": "Estándar BIP-39",
    "bip39.paragraph1": "El diccionario BIP-39 consta de 2048 palabras en inglés, cuidadosamente elegidas para que respeten la norma de los 4 primeros caracteres identifican de forma única a cada palabra (no hay dos palabras con las primeras 4 letras iguales) y se evitan utilizar palabras que fonéticamente suenen igual aunque se escriban de forma distinta. Además la longitud mínima de palabra será de 3 letras. Cada palabra del diccionario es codificada con 11 bits.",
    "bip39.paragraph2": "Nuestro sistema de generación de frases ofrece un sistema único de alta entropía en el cual la probabilidad de que cada palabra ocupe una posición dentro de la frase es uniforme e igual a 1/2048.",
    "bip39.note": "Recuerde siempre el lema: Tus claves, Tus Cryptos.",
    "demo.badge": "Mockup de Extensión Chrome",
    "demo.title": "PokeBit Extension",
    "demo.subtitle": "Previsualización del flujo: Popup inicial → Vista generación (popup) → Vista importación (pestaña nueva)",
    "demo.popupSize": "Vista Popup: 420px",
    "demo.viewTab": "Ver Vista Tab Completa",
    "demo.architecture": "📐 Arquitectura MVC",
    "demo.model": "Model:",
    "demo.modelDesc": "src/lib/model.ts - Lógica de generación y derivación",
    "demo.views": "Views:",
    "demo.viewsDesc": "src/views/ - PopupMainView, PopupGenerateView, TabImportView",
    "demo.controller": "Controller:",
    "demo.controllerDesc": "Los componentes React manejan los eventos",
  },
  zh: {
    "app.title": "PokeBit",
    "app.subtitle": "高熵钱包生成器",
    "main.generate": "生成新保险库",
    "main.generate12": "生成保险库（12个词）",
    "main.generate24": "生成保险库（24个词）",
    "main.import": "导入保险库",
    "main.securityTitle": "本地安全",
    "main.securityText": "所有密钥都在您的设备上本地生成。它们永远不会发送到外部服务器。",
    "main.footer": "PokeBit  |  doctor.bitcoin  |  Cryptovault 2026",
    "generate.title": "🔐 保险库已生成",
    "generate.subtitle": "您的助记词和派生密钥",
    "generate.derivedAccounts": "🛡️ 派生账户",
    "generate.protectVault": "🔒 保护保险库",
    "generate.howItWorks": "它是如何工作的？",
    "generate.helpTitle": "军事级加密",
    "generate.helpText": "使用我们的军事级加密技术（AES-256），您的钱包信息将受到密码保护，存储在易于导出的文件中。\n\n我们建议将文件附加到电子邮件中，与其他文件一起（混合效果），发送给自己或他人。这样，您只需访问电子邮件或请求发送电子邮件的人重新发送附件，即可在云中获取您的钱包信息。\n\n这样，您将永远不会失去对钱包的访问权限，同时确保高水平的安全性。",
    "generate.helpWarning": "注意：我们不对丢失的密码负责。没有密码，将无法访问加密的钱包信息。",
    "generate.passwordPlaceholder": "密码（至少8个字符）",
    "generate.repeatPassword": "重复密码",
    "generate.exportVault": "导出保险库 (.aes)",
    "generate.generateNew": "生成新的",
    "generate.words": "个词",
    "generate.back": "返回主页",
    "generate.loading": "正在生成保险库",
    "generate.loadingMsg": "高熵生成",
    "generate.success": "保险库生成成功",
    "generate.exported": "加密文件导出成功",
    "generate.errorPassword": "您必须输入密码",
    "generate.errorPasswordLength": "密码必须至少8个字符",
    "generate.errorConfirm": "您必须确认密码",
    "generate.errorMatch": "密码不匹配",
    "import.title": "导入保险库",
    "import.subtitle": "从加密文件恢复您的钱包",
    "import.fileLabel": "📁 保险库文件",
    "import.dragHere": "将文件拖到这里",
    "import.clickSelect": "或点击选择",
    "import.onlyAes": "仅限 .aes 文件",
    "import.passwordLabel": "🔒 解密密码",
    "import.passwordPlaceholder": "输入保险库密码...",
    "import.importButton": "导入保险库",
    "import.importing": "正在解密...",
    "import.success": "保险库解密成功",
    "import.successMsg": "您的钱包已恢复",
    "import.back": "返回弹出窗口",
    "import.errorFile": "您必须选择保险库文件",
    "import.errorPassword": "您必须输入密码",
    "import.errorPasswordLength": "密码必须至少8个字符",
    "import.errorFormat": "文件必须是 .aes 格式",
    "import.errorInvalid": "文件无效或密码错误",
    "import.reset": "重置",
    "import.resetTitle": "确认重置",
    "import.resetFinalTitle": "最终确认",
    "import.resetWarning1": "您确定要重置吗？这将清除当前视图中的钱包。",
    "import.resetWarning2": "这是您的最后警告。钱包信息将从此会话中清除。如果需要，请确保已导出保险库。",
    "import.resetSuccess": "钱包重置成功",
    "import.cancel": "取消",
    "import.continue": "继续",
    "import.confirmReset": "是的，重置",
    "import.backMenu": "返回菜单",
    "import.exportNewPassword": "使用新密码导出",
    "import.newPassword": "新密码",
    "import.repeatNewPassword": "重复新密码",
    "import.exportButton": "导出保险库",
    "password.weak": "弱密码",
    "password.medium": "中等密码",
    "password.strong": "强密码",
    "seedPhrase.title": "🌱 恢复短语",
    "seedPhrase.warning": "永远不要分享这个短语。任何有访问权限的人都可以窃取您的资金。",
    "seedPhrase.copied": "助记词已复制！",
    "crypto.privateKey": "私钥",
    "crypto.publicAddress": "公共地址",
    "crypto.copied": "已复制！",
    "bip39.question": "什么是BIP-39？",
    "bip39.title": "BIP-39标准",
    "bip39.paragraph1": "BIP-39字典由2048个英语单词组成，经过精心挑选，以确保前4个字符唯一标识每个单词（没有两个单词共享相同的前4个字母），并避免使用发音相同但拼写不同的单词。此外，最小单词长度为3个字母。字典中的每个单词用11位编码。",
    "bip39.paragraph2": "我们的短语生成系统提供独特的高熵系统，其中每个单词在短语中占据某个位置的概率是均匀的，等于1/2048。",
    "bip39.note": "请记住座右铭：你的密钥，你的加密货币。",
    "demo.badge": "Chrome 扩展模型",
    "demo.title": "PokeBit 扩展",
    "demo.subtitle": "流程预览：初始弹出窗口 → 生成视图（弹出窗口）→ 导入视图（新标签页）",
    "demo.popupSize": "弹出视图：420px",
    "demo.viewTab": "查看完整标签视图",
    "demo.architecture": "📐 MVC 架构",
    "demo.model": "模型：",
    "demo.modelDesc": "src/lib/model.ts - 生成和派生逻辑",
    "demo.views": "视图：",
    "demo.viewsDesc": "src/views/ - PopupMainView, PopupGenerateView, TabImportView",
    "demo.controller": "控制器：",
    "demo.controllerDesc": "React 组件处理事件",
  },
  hi: {
    "app.title": "PokeBit",
    "app.subtitle": "उच्च एन्ट्रॉपी वॉलेट जेनरेटर",
    "main.generate": "नया वॉल्ट बनाएं",
    "main.generate12": "वॉल्ट बनाएं (12 शब्द)",
    "main.generate24": "वॉल्ट बनाएं (24 शब्द)",
    "main.import": "वॉल्ट आयात करें",
    "main.securityTitle": "स्थानीय सुरक्षा",
    "main.securityText": "सभी कुंजियां आपके डिवाइस पर स्थानीय रूप से उत्पन्न होती हैं। वे कभी बाहरी सर्वर पर नहीं भेजी जातीं।",
    "main.footer": "PokeBit  |  doctor.bitcoin  |  Cryptovault 2026",
    "generate.title": "🔐 वॉल्ट बनाया गया",
    "generate.subtitle": "आपका सीड फ्रेज और व्युत्पन्न कुंजियां",
    "generate.derivedAccounts": "🛡️ व्युत्पन्न खाते",
    "generate.protectVault": "🔒 वॉल्ट सुरक्षित करें",
    "generate.howItWorks": "यह कैसे काम करता है?",
    "generate.helpTitle": "सैन्य ग्रेड एन्क्रिप्शन",
    "generate.helpText": "हमारी सैन्य-ग्रेड एन्क्रिप्शन तकनीक (AES-256) का उपयोग करके, आपकी वॉलेट जानकारी आपके पासवर्ड द्वारा आसानी से निर्यात योग्य फ़ाइल में सुरक्षित होगी।\n\nहम अनुशंसा करते हैं कि फ़ाइल को अन्य फ़ाइलों (मिश्रण प्रभाव) के साथ ईमेल में संलग्न करें और इसे स्वयं या दूसरों को भेजें। इस तरह, आपके पास क्लाउड में आपकी वॉलेट जानकारी होगी, बस अपने ईमेल तक पहुंचकर या उस व्यक्ति से संलग्नक के साथ पुनः भेजने के लिए कहकर।\n\nइस तरह, आप उच्च स्तर की सुरक्षा सुनिश्चित करते हुए अपने वॉलेट तक पहुंच कभी नहीं खोएंगे।",
    "generate.helpWarning": "नोट: हम खोए हुए पासवर्ड के लिए जिम्मेदार नहीं हैं। पासवर्ड के बिना, एन्क्रिप्टेड वॉलेट जानकारी तक पहुंच नहीं हो सकती।",
    "generate.passwordPlaceholder": "पासवर्ड (न्यूनतम 8 अक्षर)",
    "generate.repeatPassword": "पासवर्ड दोहराएं",
    "generate.exportVault": "वॉल्ट निर्यात करें (.aes)",
    "generate.generateNew": "नया बनाएं",
    "generate.words": "शब्द",
    "generate.back": "होम पर वापस जाएं",
    "generate.loading": "वॉल्ट बना रहे हैं",
    "generate.loadingMsg": "उच्च एन्ट्रॉपी जनरेशन",
    "generate.success": "वॉल्ट सफलतापूर्वक बनाया गया",
    "generate.exported": "एन्क्रिप्टेड फ़ाइल सफलतापूर्वक निर्यात की गई",
    "generate.errorPassword": "आपको पासवर्ड दर्ज करना होगा",
    "generate.errorPasswordLength": "पासवर्ड कम से कम 8 अक्षरों का होना चाहिए",
    "generate.errorConfirm": "आपको पासवर्ड की पुष्टि करनी होगी",
    "generate.errorMatch": "पासवर्ड मेल नहीं खाते",
    "import.title": "वॉल्ट आयात करें",
    "import.subtitle": "एन्क्रिप्टेड फ़ाइल से अपना वॉलेट पुनर्स्थापित करें",
    "import.fileLabel": "📁 वॉल्ट फ़ाइल",
    "import.dragHere": "अपनी फ़ाइल यहां खींचें",
    "import.clickSelect": "या चुनने के लिए क्लिक करें",
    "import.onlyAes": "केवल .aes फ़ाइलें",
    "import.passwordLabel": "🔒 डिक्रिप्शन पासवर्ड",
    "import.passwordPlaceholder": "वॉल्ट का पासवर्ड दर्ज करें...",
    "import.importButton": "वॉल्ट आयात करें",
    "import.importing": "डिक्रिप्ट हो रहा है...",
    "import.success": "वॉल्ट सफलतापूर्वक डिक्रिप्ट किया गया",
    "import.successMsg": "आपका वॉलेट पुनर्स्थापित हो गया है",
    "import.back": "पॉपअप पर वापस जाएं",
    "import.errorFile": "आपको वॉल्ट फ़ाइल चुननी होगी",
    "import.errorPassword": "आपको पासवर्ड दर्ज करना होगा",
    "import.errorPasswordLength": "पासवर्ड कम से कम 8 अक्षरों का होना चाहिए",
    "import.errorFormat": "फ़ाइल .aes प्रारूप में होनी चाहिए",
    "import.errorInvalid": "अमान्य फ़ाइल या गलत पासवर्ड",
    "import.reset": "रीसेट",
    "import.resetTitle": "रीसेट की पुष्टि करें",
    "import.resetFinalTitle": "अंतिम पुष्टि",
    "import.resetWarning1": "क्या आप वाकई रीसेट करना चाहते हैं? यह वर्तमान वॉलेट को इस व्यू से हटा देगा।",
    "import.resetWarning2": "यह आपकी अंतिम चेतावनी है। वॉलेट की जानकारी इस सत्र से हटा दी जाएगी। सुनिश्चित करें कि आपने जरूरत पड़ने पर वॉल्ट निर्यात कर लिया है।",
    "import.resetSuccess": "वॉलेट सफलतापूर्वक रीसेट किया गया",
    "import.cancel": "रद्द करें",
    "import.continue": "जारी रखें",
    "import.confirmReset": "हाँ, रीसेट करें",
    "import.backMenu": "मेनू पर वापस जाएं",
    "import.exportNewPassword": "नए पासवर्ड के साथ निर्यात करें",
    "import.newPassword": "नया पासवर्ड",
    "import.repeatNewPassword": "नया पासवर्ड दोहराएं",
    "import.exportButton": "वॉल्ट निर्यात करें",
    "password.weak": "कमजोर पासवर्ड",
    "password.medium": "मध्यम पासवर्ड",
    "password.strong": "मजबूत पासवर्ड",
    "seedPhrase.title": "🌱 रिकवरी फ्रेज",
    "seedPhrase.warning": "इस फ्रेज को कभी साझा न करें। इसका एक्सेस रखने वाला कोई भी आपके फंड चुरा सकता है।",
    "seedPhrase.copied": "सीड फ्रेज कॉपी किया गया!",
    "crypto.privateKey": "निजी कुंजी",
    "crypto.publicAddress": "सार्वजनिक पता",
    "crypto.copied": "कॉपी किया गया!",
    "bip39.question": "BIP-39 क्या है?",
    "bip39.title": "BIP-39 मानक",
    "bip39.paragraph1": "BIP-39 शब्दकोश में 2048 अंग्रेजी शब्द हैं, जिन्हें सावधानीपूर्वक चुना गया है ताकि पहले 4 अक्षर प्रत्येक शब्द को विशिष्ट रूप से पहचानें (कोई भी दो शब्द समान पहले 4 अक्षर साझा नहीं करते) और ध्वन्यात्मक रूप से समान लगने वाले शब्दों से बचा जाए भले ही वे अलग तरीके से लिखे गए हों। इसके अलावा, न्यूनतम शब्द लंबाई 3 अक्षर है। शब्दकोश में प्रत्येक शब्द 11 बिट्स के साथ एन्कोड किया गया है।",
    "bip39.paragraph2": "हमारी वाक्यांश पीढ़ी प्रणाली एक अद्वितीय उच्च-एन्ट्रॉपी प्रणाली प्रदान करती है जिसमें प्रत्येक शब्द के वाक्यांश में एक स्थान पर होने की संभावना समान और 1/2048 के बराबर है।",
    "bip39.note": "हमेशा याद रखें: आपकी चाबियाँ, आपकी क्रिप्टो।",
    "demo.badge": "क्रोम एक्सटेंशन मॉकअप",
    "demo.title": "PokeBit एक्सटेंशन",
    "demo.subtitle": "फ्लो प्रीव्यू: प्रारंभिक पॉपअप → जनरेशन व्यू (पॉपअप) → आयात व्यू (नया टैब)",
    "demo.popupSize": "पॉपअप व्यू: 420px",
    "demo.viewTab": "पूर्ण टैब व्यू देखें",
    "demo.architecture": "📐 MVC आर्किटेक्चर",
    "demo.model": "मॉडल:",
    "demo.modelDesc": "src/lib/model.ts - जनरेशन और डेरिवेशन लॉजिक",
    "demo.views": "व्यूज:",
    "demo.viewsDesc": "src/views/ - PopupMainView, PopupGenerateView, TabImportView",
    "demo.controller": "कंट्रोलर:",
    "demo.controllerDesc": "React कंपोनेंट्स इवेंट्स को हैंडल करते हैं",
  },
  ru: {
    "app.title": "PokeBit",
    "app.subtitle": "Генератор кошельков высокой энтропии",
    "main.generate": "СОЗДАТЬ НОВОЕ ХРАНИЛИЩЕ",
    "main.generate12": "СОЗДАТЬ ХРАНИЛИЩЕ (12 СЛОВ)",
    "main.generate24": "СОЗДАТЬ ХРАНИЛИЩЕ (24 СЛОВА)",
    "main.import": "ИМПОРТИРОВАТЬ ХРАНИЛИЩЕ",
    "main.securityTitle": "Локальная безопасность",
    "main.securityText": "Все ключи генерируются локально на вашем устройстве. Они никогда не отправляются на внешние серверы.",
    "main.footer": "PokeBit  |  doctor.bitcoin  |  Cryptovault 2026",
    "generate.title": "🔐 Хранилище создано",
    "generate.subtitle": "Ваша сид-фраза и производные ключи",
    "generate.derivedAccounts": "🛡️ Производные аккаунты",
    "generate.protectVault": "🔒 Защитить хранилище",
    "generate.howItWorks": "Как это работает?",
    "generate.helpTitle": "Шифрование военного уровня",
    "generate.helpText": "Используя нашу технологию шифрования военного уровня (AES-256), информация о ваших кошельках будет защищена паролем в легко экспортируемом файле.\n\nМы рекомендуем прикрепить файл к электронному письму вместе с другими файлами (эффект смешивания) и отправить его себе или другим. Таким образом, информация о ваших кошельках будет в облаке, доступная просто через доступ к электронной почте или попросив отправителя переслать письмо с вложениями.\n\nТаким образом, вы никогда не потеряете доступ к своим кошелькам, обеспечивая высокий уровень безопасности.",
    "generate.helpWarning": "Примечание: Мы не несем ответственности за утерянные пароли. Без пароля доступ к зашифрованной информации кошелька невозможен.",
    "generate.passwordPlaceholder": "Пароль (мин. 8 символов)",
    "generate.repeatPassword": "Повторите пароль",
    "generate.exportVault": "Экспортировать хранилище (.aes)",
    "generate.generateNew": "Создать новое",
    "generate.words": "слов",
    "generate.back": "Вернуться на главную",
    "generate.loading": "Создание хранилища",
    "generate.loadingMsg": "Генерация с высокой энтропией",
    "generate.success": "Хранилище успешно создано",
    "generate.exported": "Зашифрованный файл успешно экспортирован",
    "generate.errorPassword": "Вы должны ввести пароль",
    "generate.errorPasswordLength": "Пароль должен содержать не менее 8 символов",
    "generate.errorConfirm": "Вы должны подтвердить пароль",
    "generate.errorMatch": "Пароли не совпадают",
    "import.title": "Импортировать хранилище",
    "import.subtitle": "Восстановите кошелек из зашифрованного файла",
    "import.fileLabel": "📁 Файл хранилища",
    "import.dragHere": "Перетащите файл сюда",
    "import.clickSelect": "или нажмите для выбора",
    "import.onlyAes": "Только файлы .aes",
    "import.passwordLabel": "🔒 Пароль расшифровки",
    "import.passwordPlaceholder": "Введите пароль хранилища...",
    "import.importButton": "ИМПОРТИРОВАТЬ ХРАНИЛИЩЕ",
    "import.importing": "Расшифровка...",
    "import.success": "Хранилище успешно расшифровано",
    "import.successMsg": "Ваш кошелек восстановлен",
    "import.back": "Вернуться к попапу",
    "import.errorFile": "Вы должны выбрать файл хранилища",
    "import.errorPassword": "Вы должны ввести пароль",
    "import.errorPasswordLength": "Пароль должен содержать не менее 8 символов",
    "import.errorFormat": "Файл должен иметь расширение .aes",
    "import.errorInvalid": "Недействительный файл или неверный пароль",
    "import.reset": "Сброс",
    "import.resetTitle": "Подтвердите сброс",
    "import.resetFinalTitle": "Окончательное подтверждение",
    "import.resetWarning1": "Вы уверены, что хотите сбросить? Это удалит текущий кошелек из этого представления.",
    "import.resetWarning2": "Это ваше ПОСЛЕДНЕЕ ПРЕДУПРЕЖДЕНИЕ. Информация о кошельке будет удалена из этого сеанса. Убедитесь, что вы экспортировали хранилище, если это необходимо.",
    "import.resetSuccess": "Кошелек успешно сброшен",
    "import.cancel": "Отмена",
    "import.continue": "Продолжить",
    "import.confirmReset": "Да, сбросить",
    "import.backMenu": "Вернуться в меню",
    "import.exportNewPassword": "Экспорт с новым паролем",
    "import.newPassword": "Новый пароль",
    "import.repeatNewPassword": "Повторите новый пароль",
    "import.exportButton": "Экспортировать хранилище",
    "password.weak": "Слабый пароль",
    "password.medium": "Средний пароль",
    "password.strong": "Сильный пароль",
    "seedPhrase.title": "🌱 Фраза восстановления",
    "seedPhrase.warning": "Никогда не делитесь этой фразой. Любой, кто имеет к ней доступ, может украсть ваши средства.",
    "seedPhrase.copied": "Сид-фраза скопирована!",
    "crypto.privateKey": "Приватный ключ",
    "crypto.publicAddress": "Публичный адрес",
    "crypto.copied": "Скопировано!",
    "bip39.question": "Что такое BIP-39?",
    "bip39.title": "Стандарт BIP-39",
    "bip39.paragraph1": "Словарь BIP-39 состоит из 2048 английских слов, тщательно подобранных так, чтобы первые 4 символа уникально идентифицировали каждое слово (нет двух слов с одинаковыми первыми 4 буквами), и избегались слова, звучащие одинаково фонетически, даже если они пишутся по-разному. Кроме того, минимальная длина слова составляет 3 буквы. Каждое слово в словаре закодировано 11 битами.",
    "bip39.paragraph2": "Наша система генерации фраз предлагает уникальную систему высокой энтропии, в которой вероятность того, что каждое слово займет позицию во фразе, равномерна и равна 1/2048.",
    "bip39.note": "Всегда помните девиз: Ваши ключи, Ваши криптовалюты.",
    "demo.badge": "Макет расширения Chrome",
    "demo.title": "PokeBit Расширение",
    "demo.subtitle": "Предпросмотр: Начальный попап → Генерация (попап) → Импорт (новая вкладка)",
    "demo.popupSize": "Попап: 420px",
    "demo.viewTab": "Полноэкранный вид",
    "demo.architecture": "📐 Архитектура MVC",
    "demo.model": "Модель:",
    "demo.modelDesc": "src/lib/model.ts - Логика генерации и деривации",
    "demo.views": "Представления:",
    "demo.viewsDesc": "src/views/ - PopupMainView, PopupGenerateView, TabImportView",
    "demo.controller": "Контроллер:",
    "demo.controllerDesc": "React компоненты обрабатывают события",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("pokebit-language");
    return (saved as Language) || "es";
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem("pokebit-language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
