import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "es" | "zh" | "hi" | "ru";

interface LanguageInfo {
  code: Language;
  name: string;
  flag: string;
}

export const languages: LanguageInfo[] = [
  { code: "en", name: "English", flag: "🇺🇸" },
  { code: "es", name: "Español", flag: "🇪🇸" },
  { code: "zh", name: "中文", flag: "🇨🇳" },
  { code: "hi", name: "हिन्दी", flag: "🇮🇳" },
  { code: "ru", name: "Русский", flag: "🇷🇺" },
];

const translations: Record<Language, Record<string, string>> = {
  en: {
    "app.title": "PokeBit Wallet",
    "app.subtitle": "Secure Wallet Generator",
    "main.generate": "GENERATE NEW VAULT",
    "main.import": "IMPORT VAULT",
    "main.securityTitle": "Local Security",
    "main.securityText": "All keys are generated locally on your device. They are never sent to external servers.",
    "main.footer": "PokeBit 2024 | Secure Wallet Generator",
    "generate.title": "🔐 Vault Generated",
    "generate.subtitle": "Your seed phrase and derived keys",
    "generate.derivedAccounts": "🛡️ Derived Accounts",
    "generate.protectVault": "🔒 Protect Vault",
    "generate.passwordPlaceholder": "Password (min. 8 characters)",
    "generate.repeatPassword": "Repeat password",
    "generate.exportVault": "Export Vault",
    "generate.generateNew": "Generate New",
    "generate.back": "Back to Home",
    "generate.loading": "Generating Vault",
    "generate.loadingMsg": "High Entropy Generation",
    "generate.success": "Vault generated successfully",
    "generate.exported": "File exported successfully",
    "generate.errorPassword": "You must enter a password",
    "generate.errorPasswordLength": "Password must be at least 8 characters",
    "generate.errorConfirm": "You must confirm the password",
    "generate.errorMatch": "Passwords do not match",
    "import.title": "Import Vault",
    "import.subtitle": "Restore your wallet from an exported file",
    "import.fileLabel": "📁 Vault File",
    "import.dragHere": "Drag your file here",
    "import.clickSelect": "or click to select",
    "import.onlyJson": "Only .json files",
    "import.passwordLabel": "🔒 Decryption Password",
    "import.passwordPlaceholder": "Enter the vault password...",
    "import.importButton": "IMPORT VAULT",
    "import.importing": "Importing...",
    "import.success": "Vault imported successfully",
    "import.successMsg": "Your wallet has been restored",
    "import.back": "Back to Popup",
    "import.errorFile": "You must select a vault file",
    "import.errorPassword": "You must enter the password",
    "import.errorPasswordLength": "Password must be at least 8 characters",
    "import.errorFormat": "File must have .json extension",
    "import.errorInvalid": "Invalid file or incorrect password",
    "seedPhrase.title": "🌱 Recovery Phrase",
    "seedPhrase.warning": "Never share this phrase. Anyone with access can steal your funds.",
    "seedPhrase.copied": "Seed phrase copied!",
    "crypto.privateKey": "Private Key",
    "crypto.publicAddress": "Public Address",
    "crypto.copied": "Copied!",
    "demo.badge": "Chrome Extension Mockup",
    "demo.title": "PokeBit Wallet Extension",
    "demo.subtitle": "Flow preview: Initial Popup → Generation View (popup) → Import View (new tab)",
    "demo.popupSize": "Popup View: 420px",
    "demo.viewTab": "View Full Tab View",
    "demo.architecture": "📐 MVC Architecture",
    "demo.model": "Model:",
    "demo.modelDesc": "src/lib/model.ts - Generation and derivation logic",
    "demo.views": "Views:",
    "demo.viewsDesc": "src/views/ - PopupMainView, PopupGenerateView, TabImportView",
    "demo.controller": "Controller:",
    "demo.controllerDesc": "React components handle events",
  },
  es: {
    "app.title": "PokeBit Wallet",
    "app.subtitle": "Generador Seguro de Wallets",
    "main.generate": "GENERAR NUEVA BÓVEDA",
    "main.import": "IMPORTAR BÓVEDA",
    "main.securityTitle": "Seguridad Local",
    "main.securityText": "Todas las claves se generan localmente en tu dispositivo. Nunca se envían a servidores externos.",
    "main.footer": "PokeBit 2024 | Secure Wallet Generator",
    "generate.title": "🔐 Bóveda Generada",
    "generate.subtitle": "Tu frase semilla y claves derivadas",
    "generate.derivedAccounts": "🛡️ Cuentas Derivadas",
    "generate.protectVault": "🔒 Proteger Bóveda",
    "generate.passwordPlaceholder": "Contraseña (mín. 8 caracteres)",
    "generate.repeatPassword": "Repetir contraseña",
    "generate.exportVault": "Exportar Bóveda",
    "generate.generateNew": "Generar Nueva",
    "generate.back": "Volver al Inicio",
    "generate.loading": "Generando Bóveda",
    "generate.loadingMsg": "Generación de Alta Entropía",
    "generate.success": "Bóveda generada exitosamente",
    "generate.exported": "Archivo exportado correctamente",
    "generate.errorPassword": "Debes introducir una contraseña",
    "generate.errorPasswordLength": "La contraseña debe tener al menos 8 caracteres",
    "generate.errorConfirm": "Debes confirmar la contraseña",
    "generate.errorMatch": "Las contraseñas no coinciden",
    "import.title": "Importar Bóveda",
    "import.subtitle": "Restaura tu wallet desde un archivo exportado",
    "import.fileLabel": "📁 Archivo de Bóveda",
    "import.dragHere": "Arrastra tu archivo aquí",
    "import.clickSelect": "o haz clic para seleccionar",
    "import.onlyJson": "Solo archivos .json",
    "import.passwordLabel": "🔒 Contraseña de Descifrado",
    "import.passwordPlaceholder": "Introduce la contraseña de la bóveda...",
    "import.importButton": "IMPORTAR BÓVEDA",
    "import.importing": "Importando...",
    "import.success": "Bóveda importada correctamente",
    "import.successMsg": "Tu wallet ha sido restaurada",
    "import.back": "Volver al Popup",
    "import.errorFile": "Debes seleccionar un archivo de bóveda",
    "import.errorPassword": "Debes introducir la contraseña",
    "import.errorPasswordLength": "La contraseña debe tener al menos 8 caracteres",
    "import.errorFormat": "El archivo debe tener extensión .json",
    "import.errorInvalid": "Archivo inválido o contraseña incorrecta",
    "seedPhrase.title": "🌱 Frase de Recuperación",
    "seedPhrase.warning": "Nunca compartas esta frase. Cualquiera con acceso puede robar tus fondos.",
    "seedPhrase.copied": "¡Frase semilla copiada!",
    "crypto.privateKey": "Clave Privada",
    "crypto.publicAddress": "Dirección Pública",
    "crypto.copied": "¡Copiado!",
    "demo.badge": "Mockup de Extensión Chrome",
    "demo.title": "PokeBit Wallet Extension",
    "demo.subtitle": "Previsualización del flujo: Popup inicial → Vista generación (popup) → Vista importación (pestaña nueva)",
    "demo.popupSize": "Vista Popup: 420px",
    "demo.viewTab": "Ver Vista Tab Completa",
    "demo.architecture": "📐 Arquitectura MVC",
    "demo.model": "Model:",
    "demo.modelDesc": "src/lib/model.ts - Lógica de generación y derivación",
    "demo.views": "Views:",
    "demo.viewsDesc": "src/views/ - PopupMainView, PopupGenerateView, TabImportView",
    "demo.controller": "Controller:",
    "demo.controllerDesc": "Los componentes React manejan los eventos",
  },
  zh: {
    "app.title": "PokeBit 钱包",
    "app.subtitle": "安全钱包生成器",
    "main.generate": "生成新保险库",
    "main.import": "导入保险库",
    "main.securityTitle": "本地安全",
    "main.securityText": "所有密钥都在您的设备上本地生成。它们永远不会发送到外部服务器。",
    "main.footer": "PokeBit 2024 | 安全钱包生成器",
    "generate.title": "🔐 保险库已生成",
    "generate.subtitle": "您的助记词和派生密钥",
    "generate.derivedAccounts": "🛡️ 派生账户",
    "generate.protectVault": "🔒 保护保险库",
    "generate.passwordPlaceholder": "密码（至少8个字符）",
    "generate.repeatPassword": "重复密码",
    "generate.exportVault": "导出保险库",
    "generate.generateNew": "生成新的",
    "generate.back": "返回主页",
    "generate.loading": "正在生成保险库",
    "generate.loadingMsg": "高熵生成",
    "generate.success": "保险库生成成功",
    "generate.exported": "文件导出成功",
    "generate.errorPassword": "您必须输入密码",
    "generate.errorPasswordLength": "密码必须至少8个字符",
    "generate.errorConfirm": "您必须确认密码",
    "generate.errorMatch": "密码不匹配",
    "import.title": "导入保险库",
    "import.subtitle": "从导出的文件恢复您的钱包",
    "import.fileLabel": "📁 保险库文件",
    "import.dragHere": "将文件拖到这里",
    "import.clickSelect": "或点击选择",
    "import.onlyJson": "仅限 .json 文件",
    "import.passwordLabel": "🔒 解密密码",
    "import.passwordPlaceholder": "输入保险库密码...",
    "import.importButton": "导入保险库",
    "import.importing": "正在导入...",
    "import.success": "保险库导入成功",
    "import.successMsg": "您的钱包已恢复",
    "import.back": "返回弹出窗口",
    "import.errorFile": "您必须选择保险库文件",
    "import.errorPassword": "您必须输入密码",
    "import.errorPasswordLength": "密码必须至少8个字符",
    "import.errorFormat": "文件必须是 .json 格式",
    "import.errorInvalid": "文件无效或密码错误",
    "seedPhrase.title": "🌱 恢复短语",
    "seedPhrase.warning": "永远不要分享这个短语。任何有访问权限的人都可以窃取您的资金。",
    "seedPhrase.copied": "助记词已复制！",
    "crypto.privateKey": "私钥",
    "crypto.publicAddress": "公共地址",
    "crypto.copied": "已复制！",
    "demo.badge": "Chrome 扩展模型",
    "demo.title": "PokeBit 钱包扩展",
    "demo.subtitle": "流程预览：初始弹出窗口 → 生成视图（弹出窗口）→ 导入视图（新标签页）",
    "demo.popupSize": "弹出视图：420px",
    "demo.viewTab": "查看完整标签视图",
    "demo.architecture": "📐 MVC 架构",
    "demo.model": "模型：",
    "demo.modelDesc": "src/lib/model.ts - 生成和派生逻辑",
    "demo.views": "视图：",
    "demo.viewsDesc": "src/views/ - PopupMainView, PopupGenerateView, TabImportView",
    "demo.controller": "控制器：",
    "demo.controllerDesc": "React 组件处理事件",
  },
  hi: {
    "app.title": "PokeBit वॉलेट",
    "app.subtitle": "सुरक्षित वॉलेट जेनरेटर",
    "main.generate": "नया वॉल्ट बनाएं",
    "main.import": "वॉल्ट आयात करें",
    "main.securityTitle": "स्थानीय सुरक्षा",
    "main.securityText": "सभी कुंजियां आपके डिवाइस पर स्थानीय रूप से उत्पन्न होती हैं। वे कभी बाहरी सर्वर पर नहीं भेजी जातीं।",
    "main.footer": "PokeBit 2024 | सुरक्षित वॉलेट जेनरेटर",
    "generate.title": "🔐 वॉल्ट बनाया गया",
    "generate.subtitle": "आपका सीड फ्रेज और व्युत्पन्न कुंजियां",
    "generate.derivedAccounts": "🛡️ व्युत्पन्न खाते",
    "generate.protectVault": "🔒 वॉल्ट सुरक्षित करें",
    "generate.passwordPlaceholder": "पासवर्ड (न्यूनतम 8 अक्षर)",
    "generate.repeatPassword": "पासवर्ड दोहराएं",
    "generate.exportVault": "वॉल्ट निर्यात करें",
    "generate.generateNew": "नया बनाएं",
    "generate.back": "होम पर वापस जाएं",
    "generate.loading": "वॉल्ट बना रहे हैं",
    "generate.loadingMsg": "उच्च एन्ट्रॉपी जनरेशन",
    "generate.success": "वॉल्ट सफलतापूर्वक बनाया गया",
    "generate.exported": "फ़ाइल सफलतापूर्वक निर्यात की गई",
    "generate.errorPassword": "आपको पासवर्ड दर्ज करना होगा",
    "generate.errorPasswordLength": "पासवर्ड कम से कम 8 अक्षरों का होना चाहिए",
    "generate.errorConfirm": "आपको पासवर्ड की पुष्टि करनी होगी",
    "generate.errorMatch": "पासवर्ड मेल नहीं खाते",
    "import.title": "वॉल्ट आयात करें",
    "import.subtitle": "निर्यात की गई फ़ाइल से अपना वॉलेट पुनर्स्थापित करें",
    "import.fileLabel": "📁 वॉल्ट फ़ाइल",
    "import.dragHere": "अपनी फ़ाइल यहां खींचें",
    "import.clickSelect": "या चुनने के लिए क्लिक करें",
    "import.onlyJson": "केवल .json फ़ाइलें",
    "import.passwordLabel": "🔒 डिक्रिप्शन पासवर्ड",
    "import.passwordPlaceholder": "वॉल्ट का पासवर्ड दर्ज करें...",
    "import.importButton": "वॉल्ट आयात करें",
    "import.importing": "आयात हो रहा है...",
    "import.success": "वॉल्ट सफलतापूर्वक आयात किया गया",
    "import.successMsg": "आपका वॉलेट पुनर्स्थापित हो गया है",
    "import.back": "पॉपअप पर वापस जाएं",
    "import.errorFile": "आपको वॉल्ट फ़ाइल चुननी होगी",
    "import.errorPassword": "आपको पासवर्ड दर्ज करना होगा",
    "import.errorPasswordLength": "पासवर्ड कम से कम 8 अक्षरों का होना चाहिए",
    "import.errorFormat": "फ़ाइल .json प्रारूप में होनी चाहिए",
    "import.errorInvalid": "अमान्य फ़ाइल या गलत पासवर्ड",
    "seedPhrase.title": "🌱 रिकवरी फ्रेज",
    "seedPhrase.warning": "इस फ्रेज को कभी साझा न करें। इसका एक्सेस रखने वाला कोई भी आपके फंड चुरा सकता है।",
    "seedPhrase.copied": "सीड फ्रेज कॉपी किया गया!",
    "crypto.privateKey": "निजी कुंजी",
    "crypto.publicAddress": "सार्वजनिक पता",
    "crypto.copied": "कॉपी किया गया!",
    "demo.badge": "क्रोम एक्सटेंशन मॉकअप",
    "demo.title": "PokeBit वॉलेट एक्सटेंशन",
    "demo.subtitle": "फ्लो प्रीव्यू: प्रारंभिक पॉपअप → जनरेशन व्यू (पॉपअप) → आयात व्यू (नया टैब)",
    "demo.popupSize": "पॉपअप व्यू: 420px",
    "demo.viewTab": "पूर्ण टैब व्यू देखें",
    "demo.architecture": "📐 MVC आर्किटेक्चर",
    "demo.model": "मॉडल:",
    "demo.modelDesc": "src/lib/model.ts - जनरेशन और डेरिवेशन लॉजिक",
    "demo.views": "व्यूज:",
    "demo.viewsDesc": "src/views/ - PopupMainView, PopupGenerateView, TabImportView",
    "demo.controller": "कंट्रोलर:",
    "demo.controllerDesc": "React कंपोनेंट्स इवेंट्स को हैंडल करते हैं",
  },
  ru: {
    "app.title": "PokeBit Кошелек",
    "app.subtitle": "Безопасный генератор кошельков",
    "main.generate": "СОЗДАТЬ НОВОЕ ХРАНИЛИЩЕ",
    "main.import": "ИМПОРТИРОВАТЬ ХРАНИЛИЩЕ",
    "main.securityTitle": "Локальная безопасность",
    "main.securityText": "Все ключи генерируются локально на вашем устройстве. Они никогда не отправляются на внешние серверы.",
    "main.footer": "PokeBit 2024 | Безопасный генератор кошельков",
    "generate.title": "🔐 Хранилище создано",
    "generate.subtitle": "Ваша сид-фраза и производные ключи",
    "generate.derivedAccounts": "🛡️ Производные аккаунты",
    "generate.protectVault": "🔒 Защитить хранилище",
    "generate.passwordPlaceholder": "Пароль (мин. 8 символов)",
    "generate.repeatPassword": "Повторите пароль",
    "generate.exportVault": "Экспортировать хранилище",
    "generate.generateNew": "Создать новое",
    "generate.back": "Вернуться на главную",
    "generate.loading": "Создание хранилища",
    "generate.loadingMsg": "Генерация с высокой энтропией",
    "generate.success": "Хранилище успешно создано",
    "generate.exported": "Файл успешно экспортирован",
    "generate.errorPassword": "Вы должны ввести пароль",
    "generate.errorPasswordLength": "Пароль должен содержать не менее 8 символов",
    "generate.errorConfirm": "Вы должны подтвердить пароль",
    "generate.errorMatch": "Пароли не совпадают",
    "import.title": "Импортировать хранилище",
    "import.subtitle": "Восстановите кошелек из экспортированного файла",
    "import.fileLabel": "📁 Файл хранилища",
    "import.dragHere": "Перетащите файл сюда",
    "import.clickSelect": "или нажмите для выбора",
    "import.onlyJson": "Только файлы .json",
    "import.passwordLabel": "🔒 Пароль расшифровки",
    "import.passwordPlaceholder": "Введите пароль хранилища...",
    "import.importButton": "ИМПОРТИРОВАТЬ ХРАНИЛИЩЕ",
    "import.importing": "Импортирование...",
    "import.success": "Хранилище успешно импортировано",
    "import.successMsg": "Ваш кошелек восстановлен",
    "import.back": "Вернуться к попапу",
    "import.errorFile": "Вы должны выбрать файл хранилища",
    "import.errorPassword": "Вы должны ввести пароль",
    "import.errorPasswordLength": "Пароль должен содержать не менее 8 символов",
    "import.errorFormat": "Файл должен иметь расширение .json",
    "import.errorInvalid": "Недействительный файл или неверный пароль",
    "seedPhrase.title": "🌱 Фраза восстановления",
    "seedPhrase.warning": "Никогда не делитесь этой фразой. Любой, кто имеет к ней доступ, может украсть ваши средства.",
    "seedPhrase.copied": "Сид-фраза скопирована!",
    "crypto.privateKey": "Приватный ключ",
    "crypto.publicAddress": "Публичный адрес",
    "crypto.copied": "Скопировано!",
    "demo.badge": "Макет расширения Chrome",
    "demo.title": "PokeBit Кошелек Расширение",
    "demo.subtitle": "Предпросмотр: Начальный попап → Генерация (попап) → Импорт (новая вкладка)",
    "demo.popupSize": "Попап: 420px",
    "demo.viewTab": "Полноэкранный вид",
    "demo.architecture": "📐 Архитектура MVC",
    "demo.model": "Модель:",
    "demo.modelDesc": "src/lib/model.ts - Логика генерации и деривации",
    "demo.views": "Представления:",
    "demo.viewsDesc": "src/views/ - PopupMainView, PopupGenerateView, TabImportView",
    "demo.controller": "Контроллер:",
    "demo.controllerDesc": "React компоненты обрабатывают события",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("pokebit-language");
    return (saved as Language) || "es";
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem("pokebit-language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
